const BT = "`";
const BT3 = "```";

export const skill = [
  "# Revision Guide Skill",
  "",
  "Generate a comprehensive, beautifully styled HTML revision guide for any college module or subject. Reads all lecture pages, exam analysis, and concept pages to produce a self-contained HTML page with exam weight badges, comparison tables, memory hooks, SVG diagrams, step-by-step methods, interactive nav, and a quick-fire checklist. Uses the kami design language (warm parchment, ink-blue accent, serif-led hierarchy). Also generates a markdown companion.",
  "",
  '**Triggers:** "revision guide", "study guide", "exam prep", "revision page", "make me a revision", "create a study guide for [module]".',
  "",
  "## Workflow",
  "",
  "### Step 1: Identify the module",
  "",
  "1. Ask the user which module/subject the revision guide is for (if not already stated)",
  `2. Confirm the module path exists under ${BT}college/{Module Name}/${BT}`,
  `3. Read the module ${BT}overview.md${BT} to understand scope, assessment, and linked pages`,
  `4. Read ${BT}pastpapers/exam-analysis.md${BT} if it exists — this is critical for exam weight annotations`,
  "",
  "### Step 2: Read all source content",
  "",
  "Read all of these in parallel:",
  "",
  `- All lecture pages from ${BT}lectures/${BT} (each has exam focus annotations, key concepts, tables, memory hooks)`,
  `- All concept pages from ${BT}concepts/${BT} for deeper definitions`,
  `- The exam analysis page from ${BT}pastpapers/exam-analysis.md${BT} for topic frequency map`,
  "",
  "### Step 3: Synthesize and structure",
  "",
  "Organize the content into a coherent revision guide structured by week/topic. For each topic, extract:",
  "",
  "- **Exam weight** — from the exam analysis frequency map (Always / Very High / Regular / Occasional)",
  "- **Key concepts** — distilled from lectures, with comparison tables where applicable",
  "- **Memory hooks** — extract or create memorable hooks (💡 blocks from lectures)",
  "- **Exam-critical warnings** — common examiner traps, high-value topics",
  "- **Quick-fire checklist** — questions the student should be able to answer",
  "",
  "### Step 3.5: Map diagrams to topics (if applicable)",
  "",
  "For modules with visual/spatial concepts (economics, networks, databases, maths, etc.), map each topic to the relevant SVG diagram. See the diagram mapping tables below for reference.",
  "",
  "**Economics diagram mapping (microeconomics):**",
  "",
  "| Week | Topic | Diagrams from Reference |",
  "|------|-------|------------------------|",
  "| 1 | Scarcity, choice, opportunity cost | PPF (production possibility frontier) |",
  "| 2 | Demand & Supply basics | Demand & Supply Equilibrium, Demand Shift |",
  "| 3 | Market equilibrium | Supply Shift |",
  "| 4 | Elasticities | PED: Elastic vs Inelastic (side-by-side) |",
  "| 5 | Taxes & Subsidies | Tax Incidence, Subsidy |",
  "| — | Price controls | Price Ceiling, Price Floor |",
  "| 6 | Cost of Production | Cost Curves (MC, ATC, AVC, AFC) |",
  "| 7 | Market Failure / Externalities | Negative Externality, Positive Externality |",
  "",
  "**Non-economics diagrams:** For other modules, create simple inline SVG diagrams where they improve understanding:",
  "- **Networks**: Star/bus/ring/mesh topology diagrams (boxes connected by lines)",
  "- **ER Diagrams**: Entity rectangles with relationship diamonds (already covered in lecture content)",
  "- **Business Mathematics**: Coordinate axes with curves for graphing topics",
  "- **Organisational structures**: Hierarchy charts (boxes in tree layout)",
  "",
  "**Rules for diagrams:**",
  "- One diagram = one concept. Never crowd multiple concepts into one SVG.",
  "- Every diagram must have a " + BT + "<figcaption>" + BT + " explaining what it shows.",
  "- Place diagrams right after the paragraph that introduces the concept.",
  "- Color consistently: Demand = blue, Supply = red, Government = amber, Subsidy/Social optimum = green.",
  "- Always label axes, curves, equilibrium points, and shift arrows.",
  "",
  "### Step 4: Generate the markdown reading page",
  "",
  `Create ${BT}college/{Module Name}/readings/comprehensive-revision-guide.md${BT} with YAML frontmatter:`,
  "",
  `${BT3}yaml`,
  "---",
  "title: {Module Name} Comprehensive Revision Guide",
  "type: reading",
  "module: {Module Name}",
  "section: college",
  "date: YYYY-MM-DD",
  "tags: [{module-code}, revision, exam, overview]",
  "---",
  `${BT3}`,
  "",
  "Structure:",
  "- **Exam Quick Reference** — duration, marks, questions, pass mark, topic frequency map table",
  "- **Week/Topic sections** — one per lecture, each with:",
  "  - Exam weight badge",
  "  - Comparison tables (where applicable)",
  "  - Key concepts distilled",
  "  - Memory hooks",
  "  - Step-by-step methods (ER diagrams, strategic alignment, etc.)",
  "  - Exam-critical callouts",
  "- **Quick-Fire Revision Checklist** — comprehensive tick-list of everything the student should know",
  "- **Related pages** — links back to lectures, concepts, exam analysis",
  "",
  "### Step 5: Generate the HTML revision page",
  "",
  `Create ${BT}artifacts/{Module Name} Revision Guide.html${BT} — a fully self-contained, beautifully styled HTML file using the kami design language (warm parchment canvas, ink-blue accent, serif-led hierarchy), while keeping the dynamic, interactive revision guide experience with sticky nav, scroll tracking, hover effects, and card grids.`,
  "",
  "#### Required HTML design spec (kami design language):",
  "",
  "**Color scheme** (warm parchment / ink-blue palette):",
  "- Background: " + BT + "#f5f0e8" + BT + " (warm parchment)",
  "- Surfaces: " + BT + "#ffffff" + BT + " / " + BT + "#ede8de" + BT + " (warm off-white)",
  "- Borders: " + BT + "#d9d0c0" + BT + " (warm tan)",
  "- Text: " + BT + "#1a1a1a" + BT + " (deep charcoal) / " + BT + "#6b6258" + BT + " (warm gray)",
  "- Accent: " + BT + "#1e3a5f" + BT + " (ink blue) — single solid color, no gradient",
  "- Accent light: " + BT + "#e8edf4" + BT + " (ink-blue tint for backgrounds)",
  "- Tag colors: sage " + BT + "#7a9e7e" + BT + ", brick " + BT + "#b85450" + BT + ", slate " + BT + "#6b7b9e" + BT + ", plum " + BT + "#8b6f9e" + BT + ", ochre " + BT + "#c4913a" + BT + ", teal " + BT + "#4f8a8a" + BT,
  "",
  "**Typography** (serif-led):",
  "- Font stack: Charter, Georgia, Palatino, " + BT + '"Times New Roman"' + BT + ", serif — same stack for both headings and body",
  "- No separate sans-serif fallback; one typeface family per page",
  "- Heading sizes: 2.4rem (h1), 1.6rem (h2), 1.3rem (h3), 1.1rem (h4)",
  "- Body: 0.95rem, 1.55 line-height",
  "- Tight tracking for headings: letter-spacing -0.01em",
  "",
  "**Header**: Warm parchment background, bottom border with ink-blue double line, module title in serif with ink-blue color, subtitle and metadata in muted warm gray, badge pills with ink-blue border",
  "",
  "**Sticky nav**: Horizontal scrollable links to each week/topic section, with scroll-position highlight via JS — nav has ink-blue bottom bar, active link colored ink-blue with a small triangular indicator",
  "",
  "**Content cards and tables**:",
  "- " + BT + ".exam-critical" + BT + " ink-blue bordered box with " + BT + "#e8edf4" + BT + " tinted background for high-stakes warnings",
  "- " + BT + ".memory-hook" + BT + " plum-bordered box with 💡 icon and warm " + BT + "#f0ece4" + BT + " background for memory aids",
  "- " + BT + ".highlight" + BT + " blocks for callouts: ink-blue (info), ochre (important), sage (tips), brick (exam)",
  "- " + BT + ".card-grid" + BT + " for showing sets of items with subtle ink-blue border on hover and warm surface shift",
  "- Tables with " + BT + "#ede8de" + BT + " thead background, ink-blue header text, hover highlight on rows",
  "- " + BT + ".two-col" + BT + " grid layout for side-by-side content (e.g. Zara vs Tesla cases)",
  "- " + BT + ".steps" + BT + " ordered list with ink-blue numbered badges for sequential methods",
  "",
  "**Topic frequency in nav bar**: each nav item shows the exam weight via a small colored dot — brick for Always, ochre for Very High, slate for Regular, teal for Occasional",
  "",
  "**Diagrams**: For topics that have SVG diagrams mapped in Step 3.5, embed them as inline SVG with " + BT + "<figure>" + BT + " wrapping, warm " + BT + "#f5f0e8" + BT + " figure background, ink-blue thin border, italic captions",
  "",
  "**Checklist section**: Two-column grid of " + BT + ".checklist" + BT + " lists with □ prefix bullets for all revision items, checked items in ink-blue",
  "",
  "**Footer**: Thin ink-blue top border, module name in small serif, centered, attribution in warm gray",
  "",
  "**JavaScript**: Sticky nav scroll-highlight that tracks which section is in view; smooth scroll on nav link click; optional back-to-top button per section",
  "",
  "### Step 6: Update indexes and log",
  "",
  `1. Add the new reading page link to ${BT}college/{Module Name}/overview.md${BT} under Readings`,
  `2. Add to ${BT}college/index.md${BT} under the module's Readings subsection`,
  `3. Append to ${BT}log.md${BT}`,
  "",
  "## Design rules",
  "",
  "- All CSS must be inline in a single " + BT + "<style>" + BT + " block in the HTML " + BT + "<head>" + BT + " — no external dependencies",
  "- No JavaScript frameworks — vanilla JS only for the scroll-highlight nav and interactive behaviors",
  "- Responsive: tables should scroll horizontally on narrow screens if needed",
  "- The " + BT + ".two-col" + BT + " grid should collapse to single column at 640px",
  "- Use CSS " + BT + ":root" + BT + " variables for the full color palette (warm parchment / ink-blue)",
  '- Every exam weight badge should be color-coded: brick for "Always", ochre for "Very High", slate for "Regular", teal for "Occasional"',
  "- Tables must use consistent styling: " + BT + "var(--surface2)" + BT + " for " + BT + "thead" + BT + ", " + BT + "var(--border)" + BT + " for borders, hover highlight on rows",
  "- Cards in " + BT + ".card-grid" + BT + " should have subtle hover effects (translateY(-1px), ink-blue border color change, background shift to warm surface)",
  "- All interactive elements must work without a network connection (inline SVG, inline CSS, vanilla JS)",
  "",
  "## Diagram rules",
  "",
  "- All SVG must be inline — no external files or " + BT + "<img>" + BT + " tags referencing files",
  "- Use viewBox " + BT + "0 0 400 300" + BT + " as the standard canvas size (except PED comparison which uses wider layout)",
  "- Add " + BT + ".econ-diagram-figure" + BT + " styling for centered layout with italic captions, warm " + BT + "#f5f0e8" + BT + " background, ink-blue thin border",
  "- Add " + BT + ".econ-diagram" + BT + " styling with " + BT + "max-width: 480px; margin: 16px auto; display: block;" + BT,
  "- Color convention: Demand curves = " + BT + "#3b82f6" + BT + " (blue), Supply curves = " + BT + "#ef4444" + BT + " (red), Government/Tax = " + BT + "#f59e0b" + BT + " (amber), Subsidy/Social optimum = " + BT + "#34d399" + BT + " (green), Social cost/benefit = " + BT + "#8b5cf6" + BT + " (purple)",
  "- Label every axis, curve, equilibrium point, and shaded area",
  "- Use stroke-dasharray for shifted curves (original = dashed, new = solid)",
  "- Shaded triangles for DWL, welfare gain, surplus, shortage must use semi-transparent fills (e.g. " + BT + "rgba(248,113,113,0.2)" + BT + ")",
  "- Always include " + BT + "<figcaption>" + BT + " for accessibility and clarity",
  "- For non-economics modules, create simple diagrams using the same SVG conventions: rectangles for entities, lines for connections, etc.",
  "",
  "## When NOT to use this skill",
  "",
  "- User only wants a quick summary, not a full revision page",
  "- Module has no existing lectures or content in the vault",
  "- User wants a PDF or printed document (use the Presentations skill instead for that)",
].join("\n");

export default skill;
