export const reference = [
  "# PPTX Skill — Full Reference",
  "",
  "Full API reference for the PPTX skill. Loaded on demand via expandSkill('pptx').",
  "",
  "## Creating from Scratch (PptxGenJS)",
  "",
  "Use PptxGenJS when no template is available.",
  "",
  "```bash",
  "npm install -g pptxgenjs",
  "```",
  "",
  "If global install fails: `npm install -g pptxgenjs --prefix ~/.local`",
  "Then: `NODE_PATH=$(npm root -g --prefix ~/.local) node create-pptx.js`",
  "",
  "### Setup & Basic Structure",
  "```javascript",
  "const pptxgen = require(\"pptxgenjs\");",
  "let pres = new pptxgen();",
  "pres.layout = 'LAYOUT_16x9';",
  "let slide = pres.addSlide();",
  "slide.addText(\"Hello World!\", { x: 0.5, y: 0.5, fontSize: 36, color: \"363636\" });",
  "pres.writeFile({ fileName: \"Presentation.pptx\" });",
  "```",
  "",
  "### Layout Dimensions (inches)",
  "- LAYOUT_16x9: 10\" x 5.625\" (default)",
  "- LAYOUT_16x10: 10\" x 6.25\"",
  "- LAYOUT_4x3: 10\" x 7.5\"",
  "- LAYOUT_WIDE: 13.3\" x 7.5\"",
  "",
  "### Text & Formatting",
  "```javascript",
  "slide.addText(\"Simple Text\", { x: 1, y: 1, w: 8, h: 2, fontSize: 24, fontFace: \"Arial\",",
  "  color: \"363636\", bold: true, align: \"center\", valign: \"middle\" });",
  "",
  "// Character spacing",
  "slide.addText(\"SPACED TEXT\", { x: 1, y: 1, w: 8, h: 1, charSpacing: 6 });",
  "",
  "// Rich text arrays",
  "slide.addText([",
  "  { text: \"Bold \", options: { bold: true } },",
  "  { text: \"Italic \", options: { italic: true } }",
  "], { x: 1, y: 3, w: 8, h: 1 });",
  "",
  "// Multi-line (requires breakLine: true)",
  "slide.addText([",
  "  { text: \"Line 1\", options: { breakLine: true } },",
  "  { text: \"Line 2\", options: { breakLine: true } },",
  "], { x: 0.5, y: 0.5, w: 8, h: 2 });",
  "",
  "// Text box margin (set margin: 0 for precise alignment with shapes)",
  "slide.addText(\"Title\", { x: 0.5, y: 0.3, w: 9, h: 0.6, margin: 0 });",
  "```",
  "",
  "### Lists & Bullets",
  "```javascript",
  "// CORRECT: Multiple bullets with breakLine",
  "slide.addText([",
  "  { text: \"First\", options: { bullet: true, breakLine: true } },",
  "  { text: \"Second\", options: { bullet: true } }",
  "], { x: 0.5, y: 0.5, w: 8, h: 3 });",
  "",
  "// NEVER use unicode bullets (creates double bullets)",
  "// Sub-items: indentLevel: 1, Numbered: bullet: { type: \"number\" }",
  "```",
  "",
  "### Shapes",
  "```javascript",
  "slide.addShape(pres.shapes.RECTANGLE, {",
  "  x: 0.5, y: 0.8, w: 1.5, h: 3.0,",
  "  fill: { color: \"FF0000\" }, line: { color: \"000000\", width: 2 }",
  "});",
  "slide.addShape(pres.shapes.OVAL, { x: 4, y: 1, w: 2, h: 2, fill: { color: \"0000FF\" } });",
  "slide.addShape(pres.shapes.LINE, { x: 1, y: 3, w: 5, h: 0, line: { color: \"FF0000\", width: 3, dashType: \"dash\" } });",
  "slide.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: 1, y: 1, w: 3, h: 2, fill: { color: \"FFFFFF\" }, rectRadius: 0.1 });",
  "",
  "// With transparency or shadow",
  "{ fill: { color: \"0088CC\", transparency: 50 } }",
  "{ shadow: { type: \"outer\", color: \"000000\", blur: 6, offset: 2, angle: 135, opacity: 0.15 } }",
  "```",
  "",
  "Shadow: type (outer/inner), color (6-char hex, no #), blur (0-100), offset (0-200, never negative), angle (0-359), opacity (0-1).",
  "",
  "### Images",
  "```javascript",
  "slide.addImage({ path: \"chart.png\", x: 1, y: 1, w: 5, h: 3 });",
  "slide.addImage({ data: \"image/png;base64,...\", x: 1, y: 1, w: 5, h: 3 });",
  "// Sizing: { type: 'contain'|'cover'|'crop', w, h, x?, y? }",
  "```",
  "",
  "### Icons (react-icons → SVG → PNG)",
  "```javascript",
  "const { FaCheckCircle } = require(\"react-icons/fa\");",
  "const svg = ReactDOMServer.renderToStaticMarkup(React.createElement(FaCheckCircle, { color, size }));",
  "const pngBuffer = await sharp(Buffer.from(svg)).png().toBuffer();",
  "const data = \"image/png;base64,\" + pngBuffer.toString(\"base64\");",
  "slide.addImage({ data, x: 1, y: 1, w: 0.5, h: 0.5 });",
  "```",
  "",
  "### Tables",
  "```javascript",
  "slide.addTable([[ \"H1\", \"H2\" ], [ \"C1\", \"C2\" ]], {",
  "  x: 1, y: 1, w: 8, h: 2, border: { pt: 1, color: \"999999\" }, fill: { color: \"F1F1F1\" } });",
  "```",
  "",
  "### Charts",
  "```javascript",
  "slide.addChart(pres.charts.BAR, [{ name: \"Sales\", labels: [\"Q1\",\"Q2\"], values: [4500, 5500] }],",
  "  { x: 0.5, y: 0.6, w: 6, h: 3, barDir: 'col', showTitle: true, title: 'Sales' });",
  "slide.addChart(pres.charts.PIE, [{ labels: [\"A\",\"B\"], values: [35, 45] }],",
  "  { x: 7, y: 1, w: 5, h: 4, showPercent: true });",
  "// Styling: chartColors, chartArea, catGridLine, valGridLine, showValue, dataLabelPosition, dataLabelColor, legendPos",
  "```",
  "",
  "### Slide Masters",
  "```javascript",
  "pres.defineSlideMaster({ title: 'TITLE_SLIDE', background: { color: '283A5E' },",
  "  objects: [{ placeholder: { options: { name: 'title', type: 'title', x: 1, y: 2, w: 8, h: 2 } } }] });",
  "let slide = pres.addSlide({ masterName: \"TITLE_SLIDE\" });",
  "slide.addText(\"My Title\", { placeholder: \"title\" });",
  "```",
  "",
  "## Editing Workflow (Template-Based)",
  "",
  "1. Analyze: `python scripts/thumbnail.py template.pptx`, `python -m markitdown template.pptx`",
  "2. Plan slide mapping — use varied layouts, avoid repeating same layout",
  "3. Unpack: `python scripts/office/unpack.py template.pptx unpacked/`",
  "4. Build: delete unwanted slides, duplicate/reorder in `<p:sldIdLst>`",
  "5. Edit content in each slide XML (use subagents for parallel editing)",
  "6. Clean: `python scripts/clean.py unpacked/`",
  "7. Pack: `python scripts/office/pack.py unpacked/ output.pptx --original template.pptx`",
  "",
  "### Scripts Reference",
  "- unpack.py: Extract and pretty-print PPTX",
  "- add_slide.py: Duplicate slide or create from layout",
  "- clean.py: Remove orphaned files",
  "- pack.py: Repack with validation",
  "- thumbnail.py: Create visual grid of slides",
  "",
  "### XML Editing Rules",
  "- Bold all headers with `b=\"1\"` on `<a:rPr>`",
  "- Never use unicode bullets",
  "- Use `&#x201C;`/`&#x201D;` for smart quotes",
  "- Use `xml:space=\"preserve\"` on `<a:t>` with leading/trailing spaces",
  "- Use defusedxml, not xml.etree.ElementTree",
  "",
  "## Design Ideas",
  "- Pick bold palette (60-70% dominant, 1-2 supporting, 1 accent)",
  "- Dark for title/conclusion, light for content",
  "- Each slide needs visual element: image, chart, icon, or shape",
  "- Two-column, icon+text, 2x2 grids, half-bleed images, stat callouts",
  "- Typography: title 36-44pt bold, header 20-24pt bold, body 14-16pt, captions 10-12pt",
  "",
  "## QA",
  "- Content: `python -m markitdown output.pptx` — check for missing content and placeholder text",
  "- Visual: Convert to images and inspect for overlapping, overflow, contrast issues",
  "- Verification loop: generate → convert → inspect → fix → re-verify",
  "",
  "## Common Pitfalls",
  "1. NEVER use \"#\" with hex colors (corrupts file)",
  "2. NEVER encode opacity in 8-char hex — use opacity property",
  "3. Use `bullet: true` — never unicode bullet symbols",
  "4. Use `breakLine: true` between array items",
  "5. Avoid `lineSpacing` with bullets — use `paraSpaceAfter` instead",
  "6. Each presentation needs fresh `pptxgen()` instance",
  "7. NEVER reuse option objects (PptxGenJS mutates in-place). Use factory functions.",
  "8. Don't use ROUNDED_RECTANGLE with accent borders",
  "",
  "## Default Output Location",
  "Save to `artifacts/` (relative to vault root).",
  "",
  "## Dependencies",
  "- `pip install \"markitdown[pptx]\"` - text extraction",
  "- `pip install Pillow` - thumbnail grids",
  "- `npm install -g pptxgenjs` - creating from scratch",
  "- LibreOffice + Poppler for PDF conversion",
  "",
].join("\n");
