export const skill = [
  "# PPTX Skill",
  "",
  "Use this skill any time a .pptx file is involved — creating slide decks, reading/extracting text, editing existing presentations, working with templates. Trigger on \"deck\", \"slides\", \"presentation\", or .pptx filenames.",
  "",
  "## Quick Reference",
  "",
  "| Task | Guide |",
  "|------|-------|",
  "| Read/analyze content | `python -m markitdown presentation.pptx` |",
  "| Edit or create from template | See Editing Workflow below |",
  "| Create from scratch | See Creating from Scratch below |",
  "",
  "> **Script location note:** Python scripts live in this skill's source directory, not the vault.",
  "",
  "## Creating from Scratch (PptxGenJS)",
  "",
  "Use PptxGenJS when no template is available: `npm install -g pptxgenjs`",
  "",
  "Basic structure:",
  "- Create instance: `new pptxgen()`",
  "- Set layout: `LAYOUT_16x9` (default, 10x5.625\")",
  "- Add slides: `pres.addSlide()`",
  "- Add elements: `slide.addText()`, `slide.addShape()`, `slide.addImage()`, `slide.addTable()`, `slide.addChart()`",
  "- Save: `pres.writeFile({ fileName: \"output.pptx\" })`",
  "",
  "### Key Elements",
  "- **Text**: Rich text arrays with `breakLine: true` between items",
  "- **Lists**: Use `bullet: true`, never unicode bullet characters",
  "- **Shapes**: RECTANGLE, OVAL, LINE, ROUNDED_RECTANGLE (shapes.XXX)",
  "- **Images**: path/data, sizing (contain/cover/crop), rotate, transparency",
  "- **Icons**: react-icons → SVG → sharp (rasterize to PNG) → base64 → addImage",
  "- **Charts**: BAR, LINE, PIE with chartColors, showValue, dataLabelPosition",
  "",
  "### Critical Rules",
  "1. NEVER use \"#\" with hex colors (corrupts file)",
  "2. NEVER use 8-char hex colors — use opacity property instead",
  "3. NEVER reuse option objects across calls (PptxGenJS mutates in-place). Use factory functions.",
  "4. Use `bullet: true` not unicode `\\u2022`",
  "5. Use `breakLine: true` between rich text items",
  "6. `rectRadius` only works with ROUNDED_RECTANGLE",
  "7. Shadow offset must be non-negative (negative corrupts file)",
  "8. Each presentation needs fresh `pptxgen()` instance",
  "",
  "## Editing Workflow (Template-Based)",
  "",
  "1. **Analyze**: thumbnail.py + markitdown to understand template layout",
  "2. **Plan**: varied layouts — avoid repeating same slide type",
  "3. **Unpack**: `python scripts/office/unpack.py template.pptx unpacked/`",
  "4. **Build**: delete unwanted slides, duplicate/reorder in `<p:sldIdLst>`, complete all structural changes before editing content",
  "5. **Edit**: update text in each slide XML (subagents can parallel-edit slides)",
  "6. **Clean**: `python scripts/clean.py unpacked/`",
  "7. **Pack**: `python scripts/office/pack.py unpacked/ output.pptx --original template.pptx`",
  "",
  "### Scripts",
  "- unpack.py: Extract and pretty-print PPTX",
  "- add_slide.py: Duplicate slide or create from layout",
  "- clean.py: Remove orphaned files",
  "- pack.py: Repack with validation",
  "- thumbnail.py: Visual grid of slides",
  "",
  "### XML Editing",
  "- Bold headers with `b=\"1\"` on `<a:rPr>`",
  "- Use XML entities for smart quotes (`&#x201C;`/`&#x201D;`)",
  "- Use `xml:space=\"preserve\"` for leading/trailing spaces",
  "- Use defusedxml, not xml.etree.ElementTree",
  "",
  "## QA (Required)",
  "- Content: `python -m markitdown output.pptx` — check for missing content and leftover placeholders",
  "- Visual: Convert to images → inspect for overlaps, overflow, contrast issues",
  "- Verification loop: generate → inspect → fix → re-verify until clean",
  "",
  "## Expand for Full Reference",
  "For detailed API code examples (PptxGenJS full API, color palettes, chart styling, icon workflow, shadow options, image sizing modes, design ideas), call " + "`" + "expandSkill('pptx')" + "`" + ".",
  "",
  "## Default Output Location",
  "Save to `artifacts/` (relative to vault root).",
  "",
  "## Dependencies",
  "- `pip install \"markitdown[pptx]\"` - text extraction",
  "- `pip install Pillow` - thumbnail grids",
  "- `npm install -g pptxgenjs` - creating from scratch",
  "- LibreOffice + Poppler for PDF conversion",
  "",
].join("\n");

export default skill;
