const BT = "`";

export const skill = [
  "# PDF Processing Skill",
  "",
  "Use this skill whenever the user wants to do anything with PDF files: reading/extracting text/tables, merging/splitting, rotating pages, adding watermarks, creating new PDFs, filling forms, encrypting/decrypting, extracting images, OCR.",
  "",
  "## Quick Start",
  "",
  "```python",
  "from pypdf import PdfReader, PdfWriter",
  "",
  "# Read a PDF",
  'reader = PdfReader("document.pdf")',
  "print(f\"Pages: {len(reader.pages)}\")",
  "",
  "# Extract text",
  'text = ""',
  "for page in reader.pages:",
  "    text += page.extract_text()",
  "```",
  "",
  "## Python Libraries",
  "",
  "### pypdf - Basic Operations",
  "",
  "#### Merge PDFs",
  "```python",
  "from pypdf import PdfWriter, PdfReader",
  "",
  'writer = PdfWriter()',
  'for pdf_file in ["doc1.pdf", "doc2.pdf", "doc3.pdf"]:',
  "    reader = PdfReader(pdf_file)",
  "    for page in reader.pages:",
  "        writer.add_page(page)",
  "",
  'with open("merged.pdf", "wb") as output:',
  "    writer.write(output)",
  "```",
  "",
  "#### Split PDF",
  "```python",
  'reader = PdfReader("input.pdf")',
  "for i, page in enumerate(reader.pages):",
  "    writer = PdfWriter()",
  "    writer.add_page(page)",
  "    with open(f\"page_{i+1}.pdf\", \"wb\") as output:",
  "        writer.write(output)",
  "```",
  "",
  "#### Rotate Pages",
  "```python",
  'reader = PdfReader("input.pdf")',
  "writer = PdfWriter()",
  "page = reader.pages[0]",
  "page.rotate(90)",
  "writer.add_page(page)",
  'with open("rotated.pdf", "wb") as output:',
  "    writer.write(output)",
  "```",
  "",
  "### pdfplumber - Text and Table Extraction",
  "",
  "#### Extract Text with Layout",
  "```python",
  "import pdfplumber",
  "",
  'with pdfplumber.open("document.pdf") as pdf:',
  "    for page in pdf.pages:",
  "        text = page.extract_text()",
  "        print(text)",
  "```",
  "",
  "#### Extract Tables",
  "```python",
  'with pdfplumber.open("document.pdf") as pdf:',
  "    for i, page in enumerate(pdf.pages):",
  "        tables = page.extract_tables()",
  "        for j, table in enumerate(tables):",
  "            print(f\"Table {j+1} on page {i+1}:\")",
  "            for row in table:",
  "                print(row)",
  "```",
  "",
  "### reportlab - Create PDFs",
  "",
  "#### Basic PDF Creation",
  "```python",
  "from reportlab.lib.pagesizes import letter",
  "from reportlab.pdfgen import canvas",
  "",
  'c = canvas.Canvas("hello.pdf", pagesize=letter)',
  "width, height = letter",
  'c.drawString(100, height - 100, "Hello World!")',
  "c.save()",
  "```",
  "",
  "#### Create PDF with Multiple Pages",
  "```python",
  "from reportlab.lib.pagesizes import letter",
  "from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak",
  "from reportlab.lib.styles import getSampleStyleSheet",
  "",
  'doc = SimpleDocTemplate("report.pdf", pagesize=letter)',
  "styles = getSampleStyleSheet()",
  "story = []",
  'title = Paragraph("Report Title", styles["Title"])',
  "story.append(title)",
  "story.append(Spacer(1, 12))",
  "story.append(PageBreak())",
  "doc.build(story)",
  "```",
  "",
  "#### Subscripts and Superscripts",
  "",
  "IMPORTANT: Never use Unicode subscript/superscript characters (₀₁₂₃, ⁰¹²³) in ReportLab PDFs. Use XML markup tags:",
  "",
  "```python",
  "from reportlab.platypus import Paragraph",
  "",
  "# Subscripts: use <sub> tag",
  'chemical = Paragraph("H<sub>2</sub>O", styles["Normal"])',
  "",
  "# Superscripts: use <super> tag",
  'squared = Paragraph("x<super>2</super>", styles["Normal"])',
  "```",
  "",
  "## Command-Line Tools",
  "",
  "### pdftotext (poppler-utils)",
  "```bash",
  "pdftotext input.pdf output.txt",
  "pdftotext -layout input.pdf output.txt",
  "pdftotext -f 1 -l 5 input.pdf output.txt",
  "```",
  "",
  "### qpdf",
  "```bash",
  "# Merge",
  "qpdf --empty --pages file1.pdf file2.pdf -- merged.pdf",
  "# Split pages",
  "qpdf input.pdf --pages . 1-5 -- pages1-5.pdf",
  "# Rotate",
  "qpdf input.pdf output.pdf --rotate=+90:1",
  "# Remove password",
  "qpdf --password=mypassword --decrypt encrypted.pdf decrypted.pdf",
  "```",
  "",
  "## Common Tasks",
  "",
  "### Extract Text from Scanned PDFs (OCR)",
  "```python",
  "import pytesseract",
  "from pdf2image import convert_from_path",
  "",
  "images = convert_from_path(\"scanned.pdf\")",
  'text = ""',
  "for i, image in enumerate(images):",
  "    text += f\"Page {i+1}:\\n\"",
  "    text += pytesseract.image_to_string(image)",
  "    text += \"\\n\\n\"",
  "```",
  "",
  "### Add Watermark",
  "```python",
  'watermark = PdfReader("watermark.pdf").pages[0]',
  'reader = PdfReader("document.pdf")',
  "writer = PdfWriter()",
  "for page in reader.pages:",
  "    page.merge_page(watermark)",
  "    writer.add_page(page)",
  'with open("watermarked.pdf", "wb") as output:',
  "    writer.write(output)",
  "```",
  "",
  "### Extract Images",
  "```bash",
  "pdfimages -j input.pdf output_prefix",
  "```",
  "",
  "### Password Protection",
  "```python",
  'reader = PdfReader("input.pdf")',
  "writer = PdfWriter()",
  "for page in reader.pages:",
  "    writer.add_page(page)",
  'writer.encrypt("userpassword", "ownerpassword")',
  'with open("encrypted.pdf", "wb") as output:',
  "    writer.write(output)",
  "```",
  "",
  "## Quick Reference",
  "",
  "| Task | Best Tool |",
  "|------|-----------|",
  "| Merge PDFs | pypdf PdfWriter.add_page |",
  "| Split PDFs | pypdf one page per file |",
  "| Extract text | pdfplumber extract_text |",
  "| Extract tables | pdfplumber extract_tables |",
  "| Create PDFs | reportlab Canvas or Platypus |",
  "| Command line merge | qpdf --empty --pages |",
  "| OCR scanned PDFs | pytesseract + pdf2image |",
  "| Fill PDF forms | See forms.md reference doc |",
  "",
  "## Default Output Location",
  "",
  "When creating PDF files, save the final output to " + BT + "artifacts/" + BT + " (relative to vault root) by default. Use workspace tools since this is inside the workspace. Name files descriptively (e.g. " + BT + "artifacts/report.pdf" + BT + "). For intermediate/temp files during multi-step workflows, use " + BT + "tmp/" + BT + " inside the workspace. Only use " + BT + "~/Desktop/" + BT + " if the user explicitly asks.",
  "",
  "## Dependencies",
  "",
  "- " + BT + "pip install pypdf pdfplumber reportlab" + BT + " - Python libraries",
  "- " + BT + "pip install pytesseract pdf2image" + BT + " - OCR support",
  "- poppler-utils (pdftotext, pdfimages, pdftoppm)",
  "- qpdf",
  "- LibreOffice (for PDF conversion from Office formats)",
  "",
  "## Reference Docs",
  "",
  "- For advanced pypdfium2 usage, PDF form filling, and pdf-lib JavaScript library, read " + BT + "reference.md" + BT,
  "- For filling PDF forms (both fillable and non-fillable), read " + BT + "forms.md" + BT,
].join("\n");

export default skill;
