const BT = "`";

export const skill = [
  "# DOCX Skill",
  "",
  "Create, read, edit, and manipulate Word documents (.docx files). Triggers: any mention of \"Word doc\", \"word document\", \".docx\", or requests to produce professional documents with formatting like tables of contents, headings, page numbers, or letterheads.",
  "",
  "## Overview",
  "",
  "A .docx file is a ZIP archive containing XML files.",
  "",
  "## Quick Reference",
  "",
  "| Task | Approach |",
  "|------|----------|",
  "| Read/analyze content | pandoc or unpack for raw XML |",
  "| Create new document | Use docx npm package - see Creating New Documents below |",
  "| Edit existing document | Unpack → edit XML → repack - see Editing Existing Documents below |",
  "",
  "### Converting .doc to .docx",
  "",
  `Legacy ${BT}.doc${BT} files must be converted before editing:`,
  "",
  "```bash",
  "libreoffice --headless --convert-to docx document.doc",
  "```",
  "",
  "### Reading Content",
  "",
  "```bash",
  "# Text extraction with tracked changes",
  "pandoc --track-changes=all document.docx -o output.md",
  "",
  "# Raw XML access",
  `python scripts/office/unpack.py document.docx unpacked/`,
  "```",
  "",
  "### Converting to Images",
  "",
  "```bash",
  "libreoffice --headless --convert-to pdf document.docx",
  "pdftoppm -jpeg -r 150 document.pdf page",
  "```",
  "",
  "### Accepting Tracked Changes",
  "",
  "To produce a clean document with all tracked changes accepted (requires LibreOffice):",
  "",
  "```bash",
  `python scripts/accept_changes.py input.docx output.docx`,
  "```",
  "",
  "---",
  "",
  "## Creating New Documents",
  "",
  `Generate .docx files with JavaScript. Install: ${BT}npm install -g docx${BT}`,
  "",
  `### Setup`,
  "```javascript",
  `const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, ImageRun,`,
  `        Header, Footer, AlignmentType, LevelFormat, ExternalHyperlink,`,
  `        InternalHyperlink, Bookmark, FootnoteReferenceRun,`,
  `        TabStopType, TabStopPosition, Column, SectionType,`,
  `        TableOfContents, HeadingLevel, BorderStyle, WidthType, ShadingType, PageNumber, PageBreak } = require('docx');`,
  "",
  `const doc = new Document({ sections: [{ children: [/* content */] }] });`,
  `Packer.toBuffer(doc).then(buffer => fs.writeFileSync("doc.docx", buffer));`,
  "```",
  "",
  "### Validation",
  "After creating the file, validate it. If validation fails, unpack, fix the XML, and repack.",
  "```bash",
  `python scripts/office/validate.py doc.docx`,
  "```",
  "",
  "### Page Size",
  "",
  `CRITICAL: docx npm package defaults to A4, not US Letter. Always set page size explicitly.`,
  "",
  "```javascript",
  "sections: [{",
  "  properties: {",
  "    page: {",
  "      size: {",
  "        width: 12240,   // 8.5 inches in DXA",
  "        height: 15840   // 11 inches in DXA",
  "      },",
  "      margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 }",
  "    }",
  "  },",
  "  children: [/* content */]",
  "}]",
  "```",
  "",
  "**Common page sizes (DXA units, 1440 DXA = 1 inch):**",
  "",
  `| Paper | Width | Height | Content Width (1" margins) |`,
  "|-------|-------|--------|---------------------------|",
  "| US Letter | 12,240 | 15,840 | 9,360 |",
  "| A4 (default) | 11,906 | 16,838 | 9,026 |",
  "",
  "**Landscape orientation:** docx swaps width/height internally, so pass portrait dimensions:",
  "```javascript",
  "size: {",
  "  width: 12240,",
  "  height: 15840,",
  "  orientation: PageOrientation.LANDSCAPE",
  "}",
  "```",
  "",
  "### Styles (Override Built-in Headings)",
  "",
  "Use Arial as the default font (universally supported). Keep titles black for readability.",
  "",
  "```javascript",
  "const doc = new Document({",
  "  styles: {",
  "    default: { document: { run: { font: \"Arial\", size: 24 } } },",
  "    paragraphStyles: [",
  "      { id: \"Heading1\", name: \"Heading 1\", basedOn: \"Normal\", next: \"Normal\", quickFormat: true,",
  "        run: { size: 32, bold: true, font: \"Arial\" },",
  "        paragraph: { spacing: { before: 240, after: 240 }, outlineLevel: 0 } },",
  "      { id: \"Heading2\", name: \"Heading 2\", basedOn: \"Normal\", next: \"Normal\", quickFormat: true,",
  "        run: { size: 28, bold: true, font: \"Arial\" },",
  "        paragraph: { spacing: { before: 180, after: 180 }, outlineLevel: 1 } },",
  "    ]",
  "  },",
  "  sections: [{",
  "    children: [",
  "      new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun(\"Title\")] })",
  "    ]",
  "  }]",
  "});",
  "```",
  "",
  "### Lists (NEVER use unicode bullets)",
  "",
  `Always use LevelFormat.BULLET with numbering config instead of manual bullet characters:`,
  "",
  "```javascript",
  "const doc = new Document({",
  "  numbering: {",
  "    config: [",
  "      { reference: \"bullets\",",
  "        levels: [{ level: 0, format: LevelFormat.BULLET, text: \"\\u2022\", alignment: AlignmentType.LEFT,",
  "          style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },",
  "      { reference: \"numbers\",",
  "        levels: [{ level: 0, format: LevelFormat.DECIMAL, text: \"%1.\", alignment: AlignmentType.LEFT,",
  "          style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },",
  "    ]",
  "  },",
  "  sections: [{",
  "    children: [",
  "      new Paragraph({ numbering: { reference: \"bullets\", level: 0 },",
  "        children: [new TextRun(\"Bullet item\")] }),",
  "      new Paragraph({ numbering: { reference: \"numbers\", level: 0 },",
  "        children: [new TextRun(\"Numbered item\")] }),",
  "    ]",
  "  }]",
  "});",
  "```",
  "",
  "### Tables",
  "",
  `CRITICAL: Tables need dual widths - set both ${BT}columnWidths${BT} on the table AND ${BT}width${BT} on each cell.`,
  "",
  "```javascript",
  `const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };`,
  "const borders = { top: border, bottom: border, left: border, right: border };",
  "",
  "new Table({",
  `  width: { size: 9360, type: WidthType.DXA },`,
  "  columnWidths: [4680, 4680],",
  "  rows: [",
  "    new TableRow({",
  "      children: [",
  "        new TableCell({",
  "          borders,",
  "          width: { size: 4680, type: WidthType.DXA },",
  `          shading: { fill: "D5E8F0", type: ShadingType.CLEAR },`,
  "          margins: { top: 80, bottom: 80, left: 120, right: 120 },",
  `          children: [new Paragraph({ children: [new TextRun("Cell")] })]`,
  "        })",
  "      ]",
  "    })",
  "  ]",
  "})",
  "```",
  "",
  "Table width = sum of columnWidths = content width. US Letter with 1\" margins: 12240 - 2880 = 9360 DXA.",
  `Always use ${BT}WidthType.DXA${BT} — ${BT}WidthType.PERCENTAGE${BT} breaks in Google Docs.`,
  "",
  "### Images",
  "",
  "```javascript",
  `new Paragraph({`,
  "  children: [new ImageRun({",
  `    type: "png",`,
  "    data: fs.readFileSync(\"image.png\"),",
  "    transformation: { width: 200, height: 150 },",
  "    altText: { title: \"Title\", description: \"Desc\", name: \"Name\" }",
  "  })]",
  "})",
  "```",
  "",
  `### Page Breaks (PageBreak must be inside a Paragraph)`,
  "",
  "```javascript",
  "new Paragraph({ children: [new PageBreak()] })",
  "```",
  "",
  "### Hyperlinks",
  "",
  "```javascript",
  "// External link",
  "new Paragraph({",
  "  children: [new ExternalHyperlink({",
  `    children: [new TextRun({ text: "Click here", style: "Hyperlink" })],`,
  `    link: "https://example.com",`,
  "  })]",
  "})",
  "```",
  "",
  "### Footnotes",
  "",
  "```javascript",
  "const doc = new Document({",
  "  footnotes: {",
  "    1: { children: [new Paragraph(\"Source: Annual Report 2024\")] },",
  "  },",
  "  sections: [{",
  "    children: [new Paragraph({",
  "      children: [",
  `        new TextRun("Revenue grew 15%"),`,
  "        new FootnoteReferenceRun(1),",
  "      ],",
  "    })]",
  "  }]",
  "});",
  "```",
  "",
  "### Tab Stops",
  "",
  "```javascript",
  "new Paragraph({",
  `  children: [new TextRun("Company Name"), new TextRun("\\tJanuary 2025")],`,
  "  tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }],",
  "})",
  "```",
  "",
  "### Multi-Column Layouts",
  "",
  "```javascript",
  "sections: [{",
  "  properties: {",
  "    column: {",
  "      count: 2,",
  "      space: 720,",
  "      equalWidth: true,",
  "    },",
  "  },",
  "  children: [/* content */]",
  "}]",
  "```",
  "",
  "### Table of Contents",
  "",
  `CRITICAL: Headings must use HeadingLevel ONLY - no custom styles.`,
  "",
  "```javascript",
  `new TableOfContents("Table of Contents", { hyperlink: true, headingStyleRange: "1-3" })`,
  "```",
  "",
  "### Headers/Footers",
  "",
  "```javascript",
  "sections: [{",
  "  properties: {",
  "    page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } }",
  "  },",
  "  headers: {",
  `    default: new Header({ children: [new Paragraph({ children: [new TextRun("Header")] })] })`,
  "  },",
  "  footers: {",
  `    default: new Footer({ children: [new Paragraph({`,
  `      children: [new TextRun("Page "), new TextRun({ children: [PageNumber.CURRENT] })]`,
  "    })] })",
  "  },",
  "  children: [/* content */]",
  "}]",
  "```",
  "",
  "### Critical Rules for docx npm package",
  "",
  "- Set page size explicitly - defaults to A4; use US Letter (12240 x 15840 DXA) for US documents",
  "- Landscape: pass portrait dimensions - docx swaps width/height internally",
  "- Never use " + BT + "\\n" + BT + " - use separate Paragraph elements",
  "- Never use unicode bullets - use LevelFormat.BULLET with numbering config",
  "- PageBreak must be in Paragraph - standalone creates invalid XML",
  "- ImageRun requires type - always specify png/jpg/etc",
  "- Always set table width with DXA - never use WidthType.PERCENTAGE",
  "- Tables need dual widths - columnWidths array AND cell width, both must match",
  "- Table width = sum of columnWidths - for DXA, ensure they add up exactly",
  "- Always add cell margins (top: 80, bottom: 80, left: 120, right: 120)",
  "- Use ShadingType.CLEAR - never SOLID for table shading",
  "- Never use tables as dividers/rules - use border on Paragraph instead",
  "- TOC requires HeadingLevel only - no custom styles on heading paragraphs",
  "- Override built-in styles using exact IDs: Heading1, Heading2, etc.",
  "- Include outlineLevel - required for TOC (0 for H1, 1 for H2, etc.)",
  "",
  "---",
  "",
  "## Editing Existing Documents",
  "",
  "Follow all 3 steps in order.",
  "",
  "### Step 1: Unpack",
  "```bash",
  `python scripts/office/unpack.py document.docx unpacked/`,
  "```",
  "",
  "### Step 2: Edit XML",
  "",
  `Edit files in ${BT}unpacked/word/${BT}. Use the Edit tool directly for string replacement.`,
  "",
  `Use "Claude" as the author for tracked changes and comments unless otherwise specified.`,
  "",
  `CRITICAL: Use smart quotes for new content:`,
  "```xml",
  `<w:t>Here&#x2019;s a quote: &#x201C;Hello&#x201D;</w:t>`,
  "```",
  "",
  "| Entity | Character |",
  "|--------|-----------|",
  "| `&#x2018;` | left single |",
  "| `&#x2019;` | right single / apostrophe |",
  "| `&#x201C;` | left double |",
  "| `&#x201D;` | right double |",
  "",
  "### Step 3: Pack",
  "```bash",
  `python scripts/office/pack.py unpacked/ output.docx --original document.docx`,
  "```",
  "",
  "Validates with auto-repair, condenses XML, and creates DOCX.",
  "",
  "### Comments",
  "",
  `Use ${BT}scripts/comment.py${BT} to add comments/replies. Then add comment markers to document.xml.`,
  "",
  "```bash",
  `python scripts/comment.py unpacked/ 0 "Comment text"`,
  `python scripts/comment.py unpacked/ 1 "Reply text" --parent 0`,
  "```",
  "",
  "### Tracked Changes XML Reference",
  "",
  "**Insertion:**",
  "```xml",
  `<w:ins w:id="1" w:author="Claude" w:date="2025-01-01T00:00:00Z">`,
  "  <w:r><w:t>inserted text</w:t></w:r>",
  "</w:ins>",
  "```",
  "",
  "**Deletion:**",
  "```xml",
  `<w:del w:id="2" w:author="Claude" w:date="2025-01-01T00:00:00Z">`,
  "  <w:r><w:delText>deleted text</w:delText></w:r>",
  "</w:del>",
  "```",
  "",
  "---",
  "",
  "## Default Output Location",
  "",
  "When creating document files, save the final .docx to " + BT + "artifacts/" + BT + " (relative to vault root) by default. Use workspace tools since this is inside the workspace. Name files descriptively (e.g. " + BT + "artifacts/Quarterly-Report.docx" + BT + "). For temp files during editing workflows, use " + BT + "tmp/" + BT + ". Only use " + BT + "~/Desktop/" + BT + " if the user explicitly asks.",
  "",
  "---",
  "",
  "## Dependencies",
  "",
  "- pandoc: text extraction",
  "- docx: " + BT + "npm install -g docx" + BT + " (new documents)",
  "- LibreOffice: PDF conversion",
  "- Poppler (pdftoppm): for images",
].join("\n");

export default skill;
