const BT = "`";

export const skill = [
  "# XLSX Skill",
  "",
  "Use this skill any time a spreadsheet file is the primary input or output: create, read, edit, or fix .xlsx/.xlsm/.csv/.tsv files; add formulas/formatting/charts; clean messy data; convert between tabular formats.",
  "",
  "## Requirements for Outputs",
  "",
  "- Use a consistent professional font (Arial, Times New Roman)",
  "- **Zero formula errors** (#REF!, #DIV/0!, #VALUE!, #N/A, #NAME?)",
  "- When updating templates, match existing format exactly",
  "",
  "## Financial Model Color Coding Standards",
  "",
  "| Element | Color | Usage |",
  "|---------|-------|-------|",
  "| Hardcoded inputs | Blue (0,0,255) | Numbers users will change |",
  "| Formulas | Black (0,0,0) | All calculations |",
  "| Same-worksheet links | Green (0,128,0) | Cross-sheet references |",
  "| External links | Red (255,0,0) | Links to other files |",
  "| Key assumptions | Yellow background (255,255,0) | Cells needing attention |",
  "",
  "## Number Formatting Standards",
  "",
  `- Years: format as text strings ("2024" not "2,024")`,
  "- Currency: use $#,##0 format; always specify units in headers",
  "- Zeros: show as dash using $#,##0;($#,##0);-",
  "- Percentages: default to 0.0%",
  "- Multiples: format as 0.0x (EV/EBITDA, P/E)",
  "- Negative numbers: use parentheses (123)",
  "",
  "## Formula Construction Rules",
  "",
  "- Place ALL assumptions in separate cells and reference them",
  "- Never hardcode calculated values — always use Excel formulas",
  "- Verify all cell references, check for off-by-one errors",
  "- Test with edge cases (zero, negative, very large values)",
  "- Ensure no unintended circular references",
  "",
  "## Quick Reference",
  "",
  "| Task | Tool |",
  "|------|------|",
  "| Data analysis | pandas read_excel |",
  "| Formulas & formatting | openpyxl |",
  "| Formula recalculation | scripts/recalc.py (LibreOffice) |",
  "",
  "## Reading and Analyzing Data",
  "",
  "### Using pandas",
  "```python",
  "import pandas as pd",
  "",
  "# Read Excel",
  `df = pd.read_excel('file.xlsx')`,
  `all_sheets = pd.read_excel('file.xlsx', sheet_name=None)`,
  "",
  "# Analyze",
  "df.head()",
  "df.info()",
  "df.describe()",
  "```",
  "",
  "## CRITICAL: Use Formulas, Not Hardcoded Values",
  "",
  "Always use Excel formulas instead of calculating values in Python and hardcoding them.",
  "",
  "### WRONG - Hardcoding",
  "```python",
  "total = df['Sales'].sum()",
  "sheet['B10'] = total  # Hardcodes 5000",
  "```",
  "",
  "### CORRECT - Excel Formulas",
  "```python",
  "sheet['B10'] = '=SUM(B2:B9)'",
  "sheet['C5'] = '=(C4-C2)/C2'",
  "```",
  "",
  "## Creating New Excel Files",
  "",
  "```python",
  "from openpyxl import Workbook",
  "from openpyxl.styles import Font, PatternFill, Alignment",
  "",
  "wb = Workbook()",
  "sheet = wb.active",
  "",
  "sheet['A1'] = 'Hello'",
  "sheet.append(['Row', 'of', 'data'])",
  "sheet['B2'] = '=SUM(A1:A10)'",
  "",
  `sheet['A1'].font = Font(bold=True, color='FF0000')`,
  `sheet['A1'].fill = PatternFill('solid', start_color='FFFF00')`,
  "sheet.column_dimensions['A'].width = 20",
  "",
  "wb.save('output.xlsx')",
  "```",
  "",
  "## Editing Existing Excel Files",
  "",
  "```python",
  "from openpyxl import load_workbook",
  "",
  "wb = load_workbook('existing.xlsx')",
  "sheet = wb.active",
  "",
  "for sheet_name in wb.sheetnames:",
  "    sheet = wb[sheet_name]",
  "",
  "sheet['A1'] = 'New Value'",
  "sheet.insert_rows(2)",
  "sheet.delete_cols(3)",
  "wb.save('modified.xlsx')",
  "```",
  "",
  "## Recalculating Formulas",
  "",
  "Excel files created by openpyxl contain formulas as strings but not calculated values. Use LibreOffice to recalculate:",
  "",
  "```bash",
  "python scripts/recalc.py output.xlsx",
  "```",
  "",
  "The script recalculates all formulas, scans for errors (#REF!, #DIV/0!, etc.), and returns JSON with error details.",
  "",
  "```json",
  "{",
  '  "status": "success",',
  '  "total_errors": 0,',
  '  "total_formulas": 42',
  "}",
  "```",
  "",
  "## Formula Verification Checklist",
  "",
  "- Test 2-3 sample references before building full model",
  "- Confirm Excel columns match (column 64 = BL, not BK)",
  "- Remember Excel rows are 1-indexed (DataFrame row 5 = Excel row 6)",
  "- Check for NaN values with " + BT + "pd.notna()" + BT,
  "- Check denominators before using / in formulas (#DIV/0!)",
  "- Use correct format (Sheet1!A1) for cross-sheet references",
  "",
  "## Best Practices",
  "",
  "- pandas: best for data analysis, bulk operations, simple data export",
  "- openpyxl: best for complex formatting, formulas, Excel-specific features",
  "- Cell indices are 1-based (row=1, column=1 = A1)",
  "- Use data_only=True to read calculated values",
  `- Use ${BT}scripts/recalc.py${BT} to update formula values`,
  "- Specify data types to avoid inference issues with pandas",
  "",
  "## Code Style",
  "",
  "- Write minimal, concise Python code without unnecessary comments",
  "- Add comments to cells with complex formulas",
  "- Document data sources for hardcoded values",
  "",
  "## Default Output Location",
  "",
  "When creating spreadsheet files, save the final .xlsx to " + BT + "artifacts/" + BT + " (relative to vault root) by default. Use workspace tools since this is inside the workspace. Name files descriptively (e.g. " + BT + "artifacts/Financial-Model.xlsx" + BT + "). Only use " + BT + "~/Desktop/" + BT + " if the user explicitly asks.",
  "",
  "## Dependencies",
  "",
  `- ${BT}pip install pandas openpyxl${BT} - Python libraries`,
  "- LibreOffice: formula recalculation (configured via scripts/office/soffice.py)",
].join("\n");

export default skill;
