const BT = "`";

export const skill = [
  "# YouTube Video Link Finder Skill",
  "",
  "Use this skill when you need to find real, working YouTube video links for a list of topics (e.g., fixing broken links in video supplement files).",
  "",
  '**Triggers:** "find youtube videos", "fix video links", "update video links", "youtube workflow", "find video for topic".',
  "",
  "## The Problem",
  "",
  "Video supplement " + BT + ".md" + BT + " files often end up with placeholder or duplicate YouTube video IDs — the same " + BT + "watch?v=XXXXX" + BT + " copy-pasted across unrelated topics, or links to videos that no longer exist. You need to find **real, topic-specific** videos.",
  "",
  "## The Approach",
  "",
  "YouTube search results don't render useful content in the browser tool (all JavaScript). " + BT + "yt-dlp" + BT + " is usually not installed. The reliable method is using PowerShell or " + BT + "curl" + BT + " to scrape video IDs from YouTube search result pages.",
  "",
  "## Step-by-Step",
  "",
  "### 1. Build a topic list",
  "",
  "Create an array of search queries and labels. Each query should include the channel name (e.g., \"Khan Academy\", \"ACDC Leadership\", \"tutor2u\") plus the specific topic.",
  "",
  "### 2. Run the batch search script",
  "",
  "Use the builtin " + BT + "executeCommand" + BT + " tool to run a search script. On macOS/Linux, use " + BT + "curl" + BT + ":",
  "",
  "```bash",
  "# For each topic, construct a search URL and fetch results",
  'curl -s "https://www.youtube.com/results?search_query=TOPIC_QUERY&sp=EgIQAQ%3D%3D" | \\',
  "  grep -oP 'watch\\?v=[a-zA-Z0-9_-]{11}' | head -3 | sort -u",
  "```",
  "",
  "On Windows, use PowerShell:",
  "",
  "```powershell",
  "$headers = @{ \"User-Agent\" = \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36\" }",
  '$url = "https://www.youtube.com/results?search_query=TOPIC_QUERY&sp=EgIQAQ%3D%3D"',
  "$content = (Invoke-WebRequest -Uri $url -Headers $headers -UseBasicParsing).Content",
  "$content | Select-String -Pattern 'watch\\?v=[a-zA-Z0-9_-]{11}' -AllMatches |",
  "  ForEach-Object { $_.Matches.Value } | Select-Object -First 3 -Unique",
  "```",
  "",
  "The " + BT + "&sp=EgIQAQ%3D%3D" + BT + " filter restricts results to videos only (no playlists/channels).",
  "",
  "### 3. Handle empty results",
  "",
  "Some niche topics return no results. Try broader queries:",
  "- Remove the channel name: search topic alone",
  "- Use alternative keywords or synonyms",
  "- Look for related broader overview videos",
  "",
  "### 4. Verify critical videos in the browser",
  "",
  "Spot-check 3-5 videos by using the browser-control tool to navigate to them. Check the page title matches the expected topic.",
  "",
  "### 5. Write the corrected " + BT + ".md" + BT + " files",
  "",
  "Replace the video IDs in the existing file. Keep the existing layout (tables, headers, playlists) — only swap the video IDs.",
  "",
  "## Key Tips",
  "",
  "- **Always include the channel name** in the query for better accuracy (e.g., \"Khan Academy\" + topic)",
  "- **Get up to 3 unique video IDs** per topic — the first is usually the best match",
  "- **Add delays between requests** (1-2 seconds) to avoid rate limiting",
  "- **The regex " + BT + "watch\\?v=[a-zA-Z0-9_-]{11}" + BT + "** matches standard YouTube video IDs (exactly 11 characters)",
  "- **Playlist links** (" + BT + "/playlist?list=..." + BT + ") use a different URL pattern — search for " + BT + "playlist?list=" + BT + " instead",
  "- **Some topics won't have dedicated videos** — use the closest related video or a broader overview video",
  "- **Rate limiting**: If you get empty results after several successful queries, you may be rate-limited. Wait before retrying.",
  "",
  "## Known Reliable Channels (Microeconomics & Management)",
  "",
  "| Channel | Handle | Best For |",
  "|---------|--------|----------|",
  "| ACDC Leadership | @JacobAClifford | Energetic exam-focused micro/macro review |",
  "| Khan Academy | @khanacademy | Structured, in-depth lessons |",
  "| tutor2u | @tutor2u-official | A-Level/IB business & economics |",
  "| CrashCourse | @crashcourse | Big-picture context, entertaining |",
  "| EconClips | @EconClips | Short animated micro explainers |",
  "| EPM | @epm8805 | Management & business concepts |",
  "| Economicsfun | @economicsfun | Niche economics topics (Giffen goods, etc.) |",
].join("\n");

export default skill;
