export const skill = [
  "# Web Artifacts Builder Skill",
  "",
  "Build multi-component HTML artifacts using React 18 + TypeScript + Vite + Tailwind CSS + shadcn/ui. Bundle to a single self-contained HTML file.",
  "",
  "Use for complex artifacts requiring state management, routing, or shadcn/ui components. Not for simple single-file HTML/JSX.",
  "",
  "## Workflow",
  "",
  "1. Initialize a frontend project using scripts/init-artifact.sh",
  "2. Develop your artifact by editing the generated code",
  "3. Bundle all code into a single HTML file using scripts/bundle-artifact.sh",
  "4. Present the HTML file to the user",
  "5. (Optional) Test using Playwright if requested",
  "",
  "**Stack**: React 18 + TypeScript + Vite + Parcel (bundling) + Tailwind CSS + shadcn/ui",
  "",
  "## Design & Style Guidelines",
  "",
  "IMPORTANT: Avoid \"AI slop\" — excessive centered layouts, purple gradients, uniform rounded corners, and Inter font.",
  "",
  "## Quick Start",
  "",
  "### Step 1: Initialize Project",
  "",
  "```bash",
  "bash scripts/init-artifact.sh my-artifact",
  "cd my-artifact",
  "```",
  "",
  "This creates a fully configured project with:",
  "- React + TypeScript (via Vite)",
  "- Tailwind CSS 3.4.1 with shadcn/ui theming",
  "- Path aliases (@/) configured",
  "- 40+ shadcn/ui components pre-installed",
  "- All Radix UI dependencies",
  "- Parcel configured for bundling",
  "- Node 18+ compatibility",
  "",
  "### Step 2: Develop Your Artifact",
  "",
  "Edit the generated source files. Build your UI using React components and shadcn/ui.",
  "",
  "### Step 3: Bundle to Single HTML File",
  "",
  "```bash",
  "bash scripts/bundle-artifact.sh",
  "```",
  "",
  "Creates bundle.html - a self-contained artifact with all JS, CSS, and dependencies inlined. Can be shared directly.",
  "",
  "The script:",
  "- Installs bundling deps (parcel, @parcel/config-default, html-inline)",
  "- Creates .parcelrc config with path alias support",
  "- Builds with Parcel (no source maps)",
  "- Inlines all assets into single HTML using html-inline",
  "",
  "### Step 4: Share with User",
  "",
  "Present the bundled HTML file to the user.",
  "",
  "### Step 5: Testing (Optional)",
  "",
  "Only test if necessary or requested. Use Playwright or other tools to verify the artifact works.",
  "",
  "## Reference",
  "",
  "- shadcn/ui components: https://ui.shadcn.com/docs/components",
  "",
  "## Default Output Location",
  "",
  "When building HTML artifacts, save the final bundle.html to " + "`" + "artifacts/" + "`" + " (relative to vault root) by default. Use workspace tools since this is inside the workspace. Name files descriptively (e.g. " + "`" + "artifacts/dashboard.html" + "`" + "). Only use " + "`" + "~/Desktop/" + "`" + " if the user explicitly asks.",
  "",
  "## Dependencies",
  "",
  "- Node.js 18+",
  "- npm",
  "- bash (for init/bundle scripts)",
].join("\n");

export default skill;
