export const skill = [
  "# PPTX Skill",
  "",
  "Use this skill any time a .pptx file is involved — creating slide decks, reading/extracting text, editing existing presentations, working with templates. Trigger on \"deck\", \"slides\", \"presentation\", or .pptx filenames.",
  "",
  "## Quick Reference",
  "",
  "| Task | Guide |",
  "|------|-------|",
  "| Read/analyze content | " + "`" + "python -m markitdown presentation.pptx" + "`" + " |",
  "| Edit or create from template | Read editing.md |",
  "| Create from scratch | Read pptxgenjs.md |",
  "",
  "---",
  "",
  "## Reading Content",
  "",
  "```bash",
  "# Text extraction",
  "python -m markitdown presentation.pptx",
  "",
  "# Visual overview (thumbnails)",
  "python scripts/thumbnail.py presentation.pptx",
  "",
  "# Raw XML access",
  "python scripts/office/unpack.py presentation.pptx unpacked/",
  "```",
  "",
  "---",
  "",
  "## Editing Workflow",
  "",
  "Read editing.md for full details.",
  "",
  "1. Analyze template with thumbnail.py",
  "2. Unpack → manipulate slides → edit content → clean → pack",
  "",
  "---",
  "",
  "## Creating from Scratch",
  "",
  "Read pptxgenjs.md for full details. Use PptxGenJS library when no template or reference presentation is available.",
  "",
  "```bash",
  "npm install -g pptxgenjs",
  "```",
  "",
  "---",
  "",
  "## Design Ideas",
  "",
  "Don't create boring slides. Plain bullets on white background won't impress anyone.",
  "",
  "### Before Starting",
  "",
  "- Pick a bold, content-informed color palette",
  "- One color should dominate (60-70%), with 1-2 supporting tones and one sharp accent",
  "- Dark/light contrast: dark for title + conclusion slides, light for content",
  "- Commit to a visual motif — pick ONE distinctive element and repeat it",
  "",
  "### Color Palettes",
  "",
  "| Theme | Primary | Secondary | Accent |",
  "|-------|---------|-----------|--------|",
  "| Midnight Executive | 1E2761 | CADCFC | FFFFFF |",
  "| Forest & Moss | 2C5F2D | 97BC62 | F5F5F5 |",
  "| Coral Energy | F96167 | F9E795 | 2F3C7E |",
  "| Warm Terracotta | B85042 | E7E8D1 | A7BEAE |",
  "| Ocean Gradient | 065A82 | 1C7293 | 21295C |",
  "| Charcoal Minimal | 36454F | F2F2F2 | 212121 |",
  "| Teal Trust | 028090 | 00A896 | 02C39A |",
  "| Berry & Cream | 6D2E46 | A26769 | ECE2D0 |",
  "| Sage Calm | 84B59F | 69A297 | 50808E |",
  "| Cherry Bold | 990011 | FCF6F5 | 2F3C7E |",
  "",
  "### For Each Slide",
  "",
  "- Every slide needs a visual element — image, chart, icon, or shape",
  "- Two-column layouts, icon+text rows, 2x2 or 2x3 grids, half-bleed images",
  "- Large stat callouts, comparison columns, timeline or process flow",
  "- Icons in small colored circles next to section headers",
  "",
  "### Typography",
  "",
  "| Element | Size |",
  "|---------|------|",
  "| Slide title | 36-44pt bold |",
  "| Section header | 20-24pt bold |",
  "| Body text | 14-16pt |",
  "| Captions | 10-12pt muted |",
  "",
  "### Avoid (Common Mistakes)",
  "",
  "- Don't repeat the same layout across all slides",
  "- Don't center body text (center only titles)",
  "- Don't default to blue — pick colors for the specific topic",
  "- Don't create text-only slides — add images, icons, charts",
  "- Don't use accent lines under titles (hallmark of AI-generated slides)",
  "- Don't use low-contrast elements",
  "",
  "---",
  "",
  "## QA (Required)",
  "",
  "Assume there are problems. Your job is to find them.",
  "",
  "### Content QA",
  "```bash",
  "python -m markitdown output.pptx",
  "```",
  "Check for missing content, typos, wrong order.",
  "",
  "### Visual QA",
  "",
  "Convert slides to images, then inspect using subagents for fresh eyes.",
  "",
  "```bash",
  "python scripts/office/soffice.py --headless --convert-to pdf output.pptx",
  "pdftoppm -jpeg -r 150 output.pdf slide",
  "```",
  "",
  "Check for: overlapping elements, text overflow, low contrast, uneven gaps, placeholder content.",
  "",
  "### Verification Loop",
  "",
  "1. Generate slides → Convert to images → Inspect",
  "2. List issues found (if none, look harder)",
  "3. Fix issues",
  "4. Re-verify affected slides",
  "5. Repeat until no new issues",
  "",
  "---",
  "",
  "## Default Output Location",
  "",
  "When creating presentation files, save the final .pptx to " + "`" + "artifacts/" + "`" + " (relative to vault root) by default. Use workspace tools (workspace-writeFile, workspace-copy) since this is inside the workspace. Name files descriptively (e.g. " + "`" + "artifacts/Company-Strategy-2025.pptx" + "`" + "). Only use " + "`" + "~/Desktop/" + "`" + " or another path if the user explicitly specifies a different location.",
  "",
  "---",
  "",
  "## Dependencies",
  "",
  `- ${"`"}pip install "markitdown[pptx]"${"`"} - text extraction`,
  `- ${"`"}pip install Pillow${"`"} - thumbnail grids`,
  `- ${"`"}npm install -g pptxgenjs${"`"} - creating from scratch`,
  "- LibreOffice (soffice): PDF conversion",
  "- Poppler (pdftoppm): PDF to images",
].join("\n");

export default skill;
