export const skill = [
  "# PPTX Skill",
  "",
  "Use this skill any time a .pptx file is involved — creating slide decks, reading/extracting text, editing existing presentations, working with templates. Trigger on \"deck\", \"slides\", \"presentation\", or .pptx filenames.",
  "",
  "## Quick Reference",
  "",
  "| Task | Guide |",
  "|------|-------|",
  "| Read/analyze content | " + "`" + "python -m markitdown presentation.pptx" + "`" + " |",
  "| Edit or create from template | See Editing Workflow section below |",
  "| Create from scratch | See Creating from Scratch section below |",
  "",
  "",
  "> **Script location note:** The Python scripts (thumbnail.py, unpack.py, soffice.py) and markitdown referenced below live in this skill's source directory — NOT in the vault/workspace. Running them from the vault CWD will fail. For creating slides from scratch, use the PptxGenJS approach below (write .js to vault, run with node). For content QA without markitdown, use the unzip+grep fallback described in the QA section.",
  "",
  "---",
  "",
  "## Reading Content",
  "",
  "```bash",
  "# Text extraction",
  "python -m markitdown presentation.pptx",
  "",
  "# Visual overview (thumbnails)",
  "python scripts/thumbnail.py presentation.pptx",
  "",
  "# Raw XML access",
  "python scripts/office/unpack.py presentation.pptx unpacked/",
  "```",
  "",
  "---",
  "",
  "## Creating from Scratch (PptxGenJS)",
  "",
  "Use PptxGenJS library when no template or reference presentation is available.",
  "",
  "```bash",
  "npm install -g pptxgenjs",
  "```",
  "",
  "If global install fails (EACCES permission denied), install to a user prefix:",
  "```bash",
  "npm install -g pptxgenjs --prefix ~/.local",
  "```",
  "Then when running your script, pass NODE_PATH so " + "`" + "require(\"pptxgenjs\")" + "`" + " resolves:",
  "```bash",
  "NODE_PATH=$(npm root -g --prefix ~/.local) node create-pptx.js",
  "```",
  "Or use an absolute require path: " + "`" + "const pptxgen = require(\"/Users/YourUser/.local/lib/node_modules/pptxgenjs\");" + "`" + "",
  "",
  "### Setup & Basic Structure",
  "",
  "```javascript",
  "const pptxgen = require(\"pptxgenjs\");",
  "",
  "let pres = new pptxgen();",
  "pres.layout = 'LAYOUT_16x9';  // or 'LAYOUT_16x10', 'LAYOUT_4x3', 'LAYOUT_WIDE'",
  "pres.author = 'Your Name';",
  "pres.title = 'Presentation Title';",
  "",
  "let slide = pres.addSlide();",
  "slide.addText(\"Hello World!\", { x: 0.5, y: 0.5, fontSize: 36, color: \"363636\" });",
  "",
  "pres.writeFile({ fileName: \"Presentation.pptx\" });",
  "```",
  "",
  "### Layout Dimensions",
  "",
  "Slide dimensions (coordinates in inches):",
  "- " + "`" + "LAYOUT_16x9" + "`" + ": 10\" x 5.625\" (default)",
  "- " + "`" + "LAYOUT_16x10" + "`" + ": 10\" x 6.25\"",
  "- " + "`" + "LAYOUT_4x3" + "`" + ": 10\" x 7.5\"",
  "- " + "`" + "LAYOUT_WIDE" + "`" + ": 13.3\" x 7.5\"",
  "",
  "---",
  "",
  "### Text & Formatting",
  "",
  "```javascript",
  "// Basic text",
  "slide.addText(\"Simple Text\", {",
  "  x: 1, y: 1, w: 8, h: 2, fontSize: 24, fontFace: \"Arial\",",
  "  color: \"363636\", bold: true, align: \"center\", valign: \"middle\"",
  "});",
  "",
  "// Character spacing (use charSpacing, not letterSpacing which is silently ignored)",
  "slide.addText(\"SPACED TEXT\", { x: 1, y: 1, w: 8, h: 1, charSpacing: 6 });",
  "",
  "// Rich text arrays",
  "slide.addText([",
  "  { text: \"Bold \", options: { bold: true } },",
  "  { text: \"Italic \", options: { italic: true } }",
  "], { x: 1, y: 3, w: 8, h: 1 });",
  "",
  "// Multi-line text (requires breakLine: true)",
  "slide.addText([",
  "  { text: \"Line 1\", options: { breakLine: true } },",
  "  { text: \"Line 2\", options: { breakLine: true } },",
  "  { text: \"Line 3\" }  // Last item doesn't need breakLine",
  "], { x: 0.5, y: 0.5, w: 8, h: 2 });",
  "",
  "// Text box margin (internal padding)",
  "slide.addText(\"Title\", {",
  "  x: 0.5, y: 0.3, w: 9, h: 0.6,",
  "  margin: 0  // Use 0 when aligning text with other elements like shapes or icons",
  "});",
  "```",
  "",
  "**Tip:** Text boxes have internal margin by default. Set " + "`" + "margin: 0" + "`" + " when you need text to align precisely with shapes, lines, or icons at the same x-position.",
  "",
  "---",
  "",
  "### Lists & Bullets",
  "",
  "```javascript",
  "// CORRECT: Multiple bullets",
  "slide.addText([",
  "  { text: \"First item\", options: { bullet: true, breakLine: true } },",
  "  { text: \"Second item\", options: { bullet: true, breakLine: true } },",
  "  { text: \"Third item\", options: { bullet: true } }",
  "], { x: 0.5, y: 0.5, w: 8, h: 3 });",
  "",
  "// WRONG: Never use unicode bullets",
  "slide.addText(\"\\u2022 First item\", { ... });  // Creates double bullets",
  "",
  "// Sub-items and numbered lists",
  "{ text: \"Sub-item\", options: { bullet: true, indentLevel: 1 } }",
  "{ text: \"First\", options: { bullet: { type: \"number\" }, breakLine: true } }",
  "```",
  "",
  "---",
  "",
  "### Shapes",
  "",
  "```javascript",
  "slide.addShape(pres.shapes.RECTANGLE, {",
  "  x: 0.5, y: 0.8, w: 1.5, h: 3.0,",
  "  fill: { color: \"FF0000\" }, line: { color: \"000000\", width: 2 }",
  "});",
  "",
  "slide.addShape(pres.shapes.OVAL, { x: 4, y: 1, w: 2, h: 2, fill: { color: \"0000FF\" } });",
  "",
  "slide.addShape(pres.shapes.LINE, {",
  "  x: 1, y: 3, w: 5, h: 0, line: { color: \"FF0000\", width: 3, dashType: \"dash\" }",
  "});",
  "",
  "// With transparency",
  "slide.addShape(pres.shapes.RECTANGLE, {",
  "  x: 1, y: 1, w: 3, h: 2,",
  "  fill: { color: \"0088CC\", transparency: 50 }",
  "});",
  "",
  "// Rounded rectangle (rectRadius only works with ROUNDED_RECTANGLE, not RECTANGLE)",
  "slide.addShape(pres.shapes.ROUNDED_RECTANGLE, {",
  "  x: 1, y: 1, w: 3, h: 2,",
  "  fill: { color: \"FFFFFF\" }, rectRadius: 0.1",
  "});",
  "",
  "// With shadow",
  "slide.addShape(pres.shapes.RECTANGLE, {",
  "  x: 1, y: 1, w: 3, h: 2,",
  "  fill: { color: \"FFFFFF\" },",
  "  shadow: { type: \"outer\", color: \"000000\", blur: 6, offset: 2, angle: 135, opacity: 0.15 }",
  "});",
  "```",
  "",
  "Shadow options:",
  "",
  "| Property | Type | Range | Notes |",
  "|----------|------|-------|-------|",
  "| " + "`" + "type" + "`" + " | string | \"outer\", \"inner\" | |",
  "| " + "`" + "color" + "`" + " | string | 6-char hex (e.g. \"000000\") | No # prefix, no 8-char hex — see Common Pitfalls |",
  "| " + "`" + "blur" + "`" + " | number | 0-100 pt | |",
  "| " + "`" + "offset" + "`" + " | number | 0-200 pt | **Must be non-negative** — negative values corrupt the file |",
  "| " + "`" + "angle" + "`" + " | number | 0-359 degrees | Direction the shadow falls (135 = bottom-right, 270 = upward) |",
  "| " + "`" + "opacity" + "`" + " | number | 0.0-1.0 | Use this for transparency, never encode in color string |",
  "",
  "To cast a shadow upward (e.g. on a footer bar), use " + "`" + "angle: 270" + "`" + " with a positive offset — do **not** use a negative offset.",
  "",
  "**Note**: Gradient fills are not natively supported. Use a gradient image as a background instead.",
  "",
  "---",
  "",
  "### Images",
  "",
  "```javascript",
  "// From file path",
  "slide.addImage({ path: \"images/chart.png\", x: 1, y: 1, w: 5, h: 3 });",
  "",
  "// From URL",
  "slide.addImage({ path: \"https://example.com/image.jpg\", x: 1, y: 1, w: 5, h: 3 });",
  "",
  "// From base64 (faster, no file I/O)",
  "slide.addImage({ data: \"image/png;base64,iVBORw0KGgo...\", x: 1, y: 1, w: 5, h: 3 });",
  "```",
  "",
  "#### Image Options",
  "",
  "```javascript",
  "slide.addImage({",
  "  path: \"image.png\",",
  "  x: 1, y: 1, w: 5, h: 3,",
  "  rotate: 45,",
  "  rounding: true,",
  "  transparency: 50,",
  "  flipH: true,",
  "  altText: \"Description\",",
  "  hyperlink: { url: \"https://example.com\" }",
  "});",
  "```",
  "",
  "#### Image Sizing Modes",
  "",
  "```javascript",
  "// Contain - fit inside, preserve ratio",
  "{ sizing: { type: 'contain', w: 4, h: 3 } }",
  "",
  "// Cover - fill area, preserve ratio (may crop)",
  "{ sizing: { type: 'cover', w: 4, h: 3 } }",
  "",
  "// Crop - cut specific portion",
  "{ sizing: { type: 'crop', x: 0.5, y: 0.5, w: 2, h: 2 } }",
  "```",
  "",
  "#### Supported Formats",
  "",
  "- **Standard**: PNG, JPG, GIF (animated GIFs work in Microsoft 365)",
  "- **SVG**: Works in modern PowerPoint/Microsoft 365",
  "",
  "---",
  "",
  "### Icons",
  "",
  "Use react-icons to generate SVG icons, then rasterize to PNG for universal compatibility.",
  "",
  "```javascript",
  "const React = require(\"react\");",
  "const ReactDOMServer = require(\"react-dom/server\");",
  "const sharp = require(\"sharp\");",
  "const { FaCheckCircle, FaChartLine } = require(\"react-icons/fa\");",
  "",
  "function renderIconSvg(IconComponent, color, size) {",
  "  return ReactDOMServer.renderToStaticMarkup(",
  "    React.createElement(IconComponent, { color, size: String(size) })",
  "  );",
  "}",
  "",
  "async function iconToBase64Png(IconComponent, color, size) {",
  "  const svg = renderIconSvg(IconComponent, color, size);",
  "  const pngBuffer = await sharp(Buffer.from(svg)).png().toBuffer();",
  "  return \"image/png;base64,\" + pngBuffer.toString(\"base64\");",
  "}",
  "",
  "// Add icon to slide",
  "const iconData = await iconToBase64Png(FaCheckCircle, \"#4472C4\");",
  "slide.addImage({ data: iconData, x: 1, y: 1, w: 0.5, h: 0.5 });",
  "```",
  "",
  "Install icons: " + "`" + "npm install -g react-icons react react-dom sharp" + "`" + "",
  "",
  "Popular icon sets:",
  "- " + "`" + "react-icons/fa" + "`" + " - Font Awesome",
  "- " + "`" + "react-icons/md" + "`" + " - Material Design",
  "- " + "`" + "react-icons/hi" + "`" + " - Heroicons",
  "- " + "`" + "react-icons/bi" + "`" + " - Bootstrap Icons",
  "",
  "---",
  "",
  "### Slide Backgrounds",
  "",
  "```javascript",
  "// Solid color",
  "slide.background = { color: \"F1F1F1\" };",
  "",
  "// Color with transparency",
  "slide.background = { color: \"FF3399\", transparency: 50 };",
  "",
  "// Image from URL",
  "slide.background = { path: \"https://example.com/bg.jpg\" };",
  "",
  "// Image from base64",
  "slide.background = { data: \"image/png;base64,iVBORw0KGgo...\" };",
  "```",
  "",
  "---",
  "",
  "### Tables",
  "",
  "```javascript",
  "slide.addTable([",
  "  [\"Header 1\", \"Header 2\"],",
  "  [\"Cell 1\", \"Cell 2\"]",
  "], {",
  "  x: 1, y: 1, w: 8, h: 2,",
  "  border: { pt: 1, color: \"999999\" }, fill: { color: \"F1F1F1\" }",
  "});",
  "```",
  "",
  "---",
  "",
  "### Charts",
  "",
  "```javascript",
  "// Bar chart",
  "slide.addChart(pres.charts.BAR, [{",
  "  name: \"Sales\", labels: [\"Q1\", \"Q2\", \"Q3\", \"Q4\"], values: [4500, 5500, 6200, 7100]",
  "}], {",
  "  x: 0.5, y: 0.6, w: 6, h: 3, barDir: 'col',",
  "  showTitle: true, title: 'Quarterly Sales'",
  "});",
  "",
  "// Line chart",
  "slide.addChart(pres.charts.LINE, [{",
  "  name: \"Temp\", labels: [\"Jan\", \"Feb\", \"Mar\"], values: [32, 35, 42]",
  "}], { x: 0.5, y: 4, w: 6, h: 3, lineSize: 3, lineSmooth: true });",
  "",
  "// Pie chart",
  "slide.addChart(pres.charts.PIE, [{",
  "  name: \"Share\", labels: [\"A\", \"B\", \"Other\"], values: [35, 45, 20]",
  "}], { x: 7, y: 1, w: 5, h: 4, showPercent: true });",
  "```",
  "",
  "#### Better-Looking Charts",
  "",
  "```javascript",
  "slide.addChart(pres.charts.BAR, chartData, {",
  "  x: 0.5, y: 1, w: 9, h: 4, barDir: \"col\",",
  "  chartColors: [\"0D9488\", \"14B8A6\", \"5EEAD4\"],",
  "  chartArea: { fill: { color: \"FFFFFF\" }, roundedCorners: true },",
  "  catAxisLabelColor: \"64748B\",",
  "  valAxisLabelColor: \"64748B\",",
  "  valGridLine: { color: \"E2E8F0\", size: 0.5 },",
  "  catGridLine: { style: \"none\" },",
  "  showValue: true,",
  "  dataLabelPosition: \"outEnd\",",
  "  dataLabelColor: \"1E293B\",",
  "  showLegend: false,",
  "});",
  "```",
  "",
  "**Key styling options:**",
  "- " + "`" + "chartColors" + "`" + " - hex colors for series/segments",
  "- " + "`" + "chartArea" + "`" + " - chart background",
  "- " + "`" + "catGridLine" + "`" + "/" + "`" + "valGridLine" + "`" + " - grid lines (style: \"none\" to hide)",
  "- " + "`" + "lineSmooth" + "`" + ": true - curved lines",
  "- " + "`" + "legendPos" + "`" + " - position: \"b\", \"t\", \"l\", \"r\", \"tr\"",
  "",
  "---",
  "",
  "### Slide Masters",
  "",
  "```javascript",
  "pres.defineSlideMaster({",
  "  title: 'TITLE_SLIDE', background: { color: '283A5E' },",
  "  objects: [{",
  "    placeholder: { options: { name: 'title', type: 'title', x: 1, y: 2, w: 8, h: 2 } }",
  "  }]",
  "});",
  "",
  "let titleSlide = pres.addSlide({ masterName: \"TITLE_SLIDE\" });",
  "titleSlide.addText(\"My Title\", { placeholder: \"title\" });",
  "```",
  "",
  "---",
  "",
  "### Common Pitfalls (PptxGenJS)",
  "",
  "These issues cause file corruption, visual bugs, or broken output. Avoid them.",
  "",
  "1. **NEVER use \"#\" with hex colors** - causes file corruption",
  "   - CORRECT: " + "`" + "color: \"FF0000\"" + "`" + "",
  "   - WRONG: " + "`" + "color: \"#FF0000\"" + "`" + "",
  "",
  "2. **NEVER encode opacity in hex color strings** - 8-char colors corrupt the file. Use the " + "`" + "opacity" + "`" + " property instead.",
  "",
  "3. **Use " + "`" + "bullet: true" + "`" + "** - NEVER unicode symbols like \"\\u2022\" (creates double bullets)",
  "",
  "4. **Use " + "`" + "breakLine: true" + "`" + " between array items or text runs together",
  "",
  "5. **Avoid " + "`" + "lineSpacing" + "`" + " with bullets** - causes excessive gaps; use " + "`" + "paraSpaceAfter" + "`" + " instead",
  "",
  "6. **Each presentation needs fresh instance** - don't reuse " + "`" + "pptxgen()" + "`" + " objects",
  "",
  "7. **NEVER reuse option objects across calls** - PptxGenJS mutates objects in-place. Use a factory function for shared options.",
  "   ```javascript",
  "   const makeShadow = () => ({ type: \"outer\", blur: 6, offset: 2, color: \"000000\", opacity: 0.15 });",
  "   slide.addShape(pres.shapes.RECTANGLE, { shadow: makeShadow(), ... });  // fresh object each time",
  "   ```",
  "",
  "8. **Don't use ROUNDED_RECTANGLE with accent borders** - rectangular overlay bars won't cover rounded corners. Use RECTANGLE instead.",
  "",
  "---",
  "",
  "## Editing Workflow (Template-Based)",
  "",
  "When using an existing presentation as a template:",
  "",
  "1. **Analyze existing slides**:",
  "   ```bash",
  "   python scripts/thumbnail.py template.pptx",
  "   python -m markitdown template.pptx",
  "   ```",
  "   Review thumbnails.jpg to see layouts, and markitdown output to see placeholder text.",
  "",
  "2. **Plan slide mapping**: For each content section, choose a template slide.",
  "",
  "   **USE VARIED LAYOUTS** — monotonous presentations are a common failure mode. Don't default to basic title + bullet slides. Actively seek out:",
  "   - Multi-column layouts (2-column, 3-column)",
  "   - Image + text combinations",
  "   - Full-bleed images with text overlay",
  "   - Quote or callout slides",
  "   - Section dividers",
  "   - Stat/number callouts",
  "   - Icon grids or icon + text rows",
  "",
  '   **Avoid:** Repeating the same text-heavy layout for every slide.',
  "",
  '   Match content type to layout style (e.g., key points -> bullet slide, team info -> multi-column, testimonials -> quote slide).',
  "",
  "3. **Unpack**: " + "`" + "python scripts/office/unpack.py template.pptx unpacked/" + "`" + "",
  "",
  "4. **Build presentation**:",
  "   - Delete unwanted slides (remove from " + "`" + "<p:sldIdLst>" + "`" + ")",
  "   - Duplicate slides you want to reuse (" + "`" + "add_slide.py" + "`" + ")",
  "   - Reorder slides in " + "`" + "<p:sldIdLst>" + "`" + "",
  "   - **Complete all structural changes before step 5**",
  "",
  "5. **Edit content**: Update text in each " + "`" + "slide{N}.xml" + "`" + ".",
  "   Use subagents here if available — slides are separate XML files, so subagents can edit in parallel.",
  "",
  "6. **Clean**: " + "`" + "python scripts/clean.py unpacked/" + "`" + "",
  "",
  "7. **Pack**: " + "`" + "python scripts/office/pack.py unpacked/ output.pptx --original template.pptx" + "`" + "",
  "",
  "---",
  "",
  "### Scripts Reference",
  "",
  "| Script | Purpose |",
  "|--------|---------|",
  "| " + "`" + "unpack.py" + "`" + " | Extract and pretty-print PPTX |",
  "| " + "`" + "add_slide.py" + "`" + " | Duplicate slide or create from layout |",
  "| " + "`" + "clean.py" + "`" + " | Remove orphaned files |",
  "| " + "`" + "pack.py" + "`" + " | Repack with validation |",
  "| " + "`" + "thumbnail.py" + "`" + " | Create visual grid of slides |",
  "",
  "#### unpack.py",
  "```bash",
  "python scripts/office/unpack.py input.pptx unpacked/",
  "```",
  "Extracts PPTX, pretty-prints XML, escapes smart quotes.",
  "",
  "#### add_slide.py",
  "```bash",
  "python scripts/add_slide.py unpacked/ slide2.xml       # Duplicate slide",
  "python scripts/add_slide.py unpacked/ slideLayout2.xml # From layout",
  "```",
  "Prints " + "`" + "<p:sldId>" + "`" + " to add to " + "`" + "<p:sldIdLst>" + "`" + " at desired position.",
  "",
  "#### clean.py",
  "```bash",
  "python scripts/clean.py unpacked/",
  "```",
  "Removes slides not in " + "`" + "<p:sldIdLst>" + "`" + ", unreferenced media, orphaned rels.",
  "",
  "#### pack.py",
  "```bash",
  "python scripts/office/pack.py unpacked/ output.pptx --original input.pptx",
  "```",
  "Validates, repairs, condenses XML, re-encodes smart quotes.",
  "",
  "#### thumbnail.py",
  "```bash",
  "python scripts/thumbnail.py input.pptx [output_prefix] [--cols N]",
  "```",
  "Creates thumbnails.jpg with slide filenames as labels. Default 3 columns, max 12 per grid.",
  "",
  "---",
  "",
  "### Slide Operations",
  "",
  "Slide order is in " + "`" + "ppt/presentation.xml" + "`" + " -> " + "`" + "<p:sldIdLst>" + "`" + ".",
  "",
  "- **Reorder**: Rearrange " + "`" + "<p:sldId>" + "`" + " elements.",
  "- **Delete**: Remove " + "`" + "<p:sldId>" + "`" + ", then run " + "`" + "clean.py" + "`" + ".",
  "- **Add**: Use " + "`" + "add_slide.py" + "`" + ". Never manually copy slide files — the script handles notes references, Content_Types.xml, and relationship IDs that manual copying misses.",
  "",
  "---",
  "",
  "### Editing Content in XML",
  "",
  "**Subagents:** If available, use them here (after completing structural changes). Each slide is a separate XML file, so subagents can edit in parallel. Include in the subagent prompt:",
  "- The slide file path(s) to edit",
  "- **\"Use the Edit tool for all changes\"**",
  "- The formatting rules and common pitfalls below",
  "",
  "For each slide:",
  "1. Read the slide's XML",
  "2. Identify ALL placeholder content — text, images, charts, icons, captions",
  "3. Replace each placeholder with final content",
  "",
  "**Use the Edit tool, not sed or Python scripts.**",
  "",
  "#### Formatting Rules",
  "",
  "- **Bold all headers, subheadings, and inline labels**: Use " + "`" + "b=\"1\"" + "`" + " on " + "`" + "<a:rPr>" + "`" + ". This includes slide titles, section headers within a slide, and inline labels.",
  "- **Never use unicode bullets (\\u2022)**: Use proper list formatting with " + "`" + "<a:buChar>" + "`" + " or " + "`" + "<a:buAutoNum>" + "`" + ".",
  "- **Bullet consistency**: Let bullets inherit from the layout. Only specify " + "`" + "<a:buChar>" + "`" + " or " + "`" + "<a:buNone>" + "`" + ".",
  "",
  "---",
  "",
  "### Editing Common Pitfalls",
  "",
  "**Template Adaptation:**",
  "- When source content has fewer items than the template, remove excess elements entirely (images, shapes, text boxes), don't just clear text.",
  "- Check for orphaned visuals after clearing text content.",
  "- When replacing text with longer content, test with visual QA — may overflow or wrap unexpectedly.",
  "- **Template slots != Source items**: If template has 4 team members but source has 3, delete the 4th member's entire group, not just the text.",
  "",
  "**Multi-Item Content:**",
  "If source has multiple items, create separate " + "`" + "<a:p>" + "`" + " elements for each — never concatenate into one string.",
  "",
  "**Smart Quotes:**",
  "Handled automatically by unpack/pack. But the Edit tool converts smart quotes to ASCII. When adding new text with quotes, use XML entities:",
  "",
  "| Character | Name | XML Entity |",
  "|-----------|------|------------|",
  "| \" | Left double quote | " + "`" + "&#x201C;" + "`" + " |",
  "| \" | Right double quote | " + "`" + "&#x201D;" + "`" + " |",
  "| ' | Left single quote | " + "`" + "&#x2018;" + "`" + " |",
  "| ' | Right single quote | " + "`" + "&#x2019;" + "`" + " |",
  "",
  "**Other:**",
  "- Use " + "`" + "xml:space=\"preserve\"" + "`" + " on " + "`" + "<a:t>" + "`" + " with leading/trailing spaces.",
  "- Use defusedxml, not xml.etree.ElementTree (corrupts namespaces).",
  "",
  "---",
  "",
  "## Design Ideas",
  "",
  "Don't create boring slides. Plain bullets on white background won't impress anyone.",
  "",
  "### Before Starting",
  "",
  "- Pick a bold, content-informed color palette",
  "- One color should dominate (60-70%), with 1-2 supporting tones and one sharp accent",
  "- Dark/light contrast: dark for title + conclusion slides, light for content",
  "- Commit to a visual motif — pick ONE distinctive element and repeat it",
  "",
  "### Color Palettes",
  "",
  "| Theme | Primary | Secondary | Accent |",
  "|-------|---------|-----------|--------|",
  "| Midnight Executive | 1E2761 | CADCFC | FFFFFF |",
  "| Forest & Moss | 2C5F2D | 97BC62 | F5F5F5 |",
  "| Coral Energy | F96167 | F9E795 | 2F3C7E |",
  "| Warm Terracotta | B85042 | E7E8D1 | A7BEAE |",
  "| Ocean Gradient | 065A82 | 1C7293 | 21295C |",
  "| Charcoal Minimal | 36454F | F2F2F2 | 212121 |",
  "| Teal Trust | 028090 | 00A896 | 02C39A |",
  "| Berry & Cream | 6D2E46 | A26769 | ECE2D0 |",
  "| Sage Calm | 84B59F | 69A297 | 50808E |",
  "| Cherry Bold | 990011 | FCF6F5 | 2F3C7E |",
  "",
  "### For Each Slide",
  "",
  "- Every slide needs a visual element — image, chart, icon, or shape",
  "- Two-column layouts, icon+text rows, 2x2 or 2x3 grids, half-bleed images",
  "- Large stat callouts, comparison columns, timeline or process flow",
  "- Icons in small colored circles next to section headers",
  "",
  "### Typography",
  "",
  "| Element | Size |",
  "|---------|------|",
  "| Slide title | 36-44pt bold |",
  "| Section header | 20-24pt bold |",
  "| Body text | 14-16pt |",
  "| Captions | 10-12pt muted |",
  "",
  "### Avoid (Common Mistakes)",
  "",
  "- Don't repeat the same layout across all slides",
  "- Don't center body text (center only titles)",
  "- Don't default to blue — pick colors for the specific topic",
  "- Don't create text-only slides — add images, icons, charts",
  "- Don't use accent lines under titles (hallmark of AI-generated slides)",
  "- Don't use low-contrast elements",
  "",
  "---",
  "",
  "## QA (Required)",
  "",
  "Assume there are problems. Your job is to find them.",
  "",
  "### Content QA",
  "",
  "**Preferred (requires Python 3.10+):**",
  "```bash",
  "python -m markitdown output.pptx",
  "```",
  "Check for missing content, typos, wrong order.",
  "",
  "When using templates, check for leftover placeholder text:",
  "```bash",
  "python -m markitdown output.pptx | grep -iE \"xxxx|lorem|ipsum|this.*(page|slide).*layout\"",
  "```",
  "If grep returns results, fix them before declaring success.",
  "",
  "**Fallback (Python <3.10):** If markitdown is unavailable, extract text by unzipping the PPTX (it's a ZIP archive) and grepping the slide XML:",
  "```bash",
  "unzip -q output.pptx -d /tmp/pptx-check",
  "for f in /tmp/pptx-check/ppt/slides/slide*.xml; do",
  "  echo \"=== $(basename $f) ===\"",
  "  grep -o '<a:t>[^<]*</a:t>' \"$f\"",
  "done",
  "```",
  "",
  "### Visual QA",
  "",
  "Convert slides to images, then inspect using subagents for fresh eyes.",
  "",
  "**Preferred (requires skill scripts accessible + LibreOffice + Poppler):**",
  "```bash",
  "python scripts/office/soffice.py --headless --convert-to pdf output.pptx",
  "pdftoppm -jpeg -r 150 output.pdf slide",
  "```",
  "",
  "**Alternative (no scripts needed):** Open the .pptx in PowerPoint/Google Slides and visually review, or use the content QA approach (unzip+grep XML) to verify text accuracy.",
  "",
  "Check for: overlapping elements, text overflow, low contrast, uneven gaps, placeholder content.",
  "",
  "Use this subagent prompt:",
  "```",
  "Visually inspect these slides. Assume there are issues — find them.",
  "Look for: overlapping elements, text overflow/cut off, decorative lines positioned for single-line text but title wrapped to two lines, source citations or footers colliding with content, elements too close (< 0.3\" gaps), uneven gaps, insufficient margin from slide edges (< 0.5\"), columns not aligned consistently, low-contrast text/icons, text boxes too narrow causing excessive wrapping, leftover placeholder content.",
  "Report ALL issues found, including minor ones.",
  "```",
  "",
  "### Verification Loop",
  "",
  "1. Generate slides -> Convert to images -> Inspect",
  "2. List issues found (if none, look harder)",
  "3. Fix issues",
  "4. Re-verify affected slides",
  "5. Repeat until no new issues",
  "",
  "---",
  "",
  "## Default Output Location",
  "",
  "When creating presentation files, save the final .pptx to " + "`" + "artifacts/" + "`" + " (relative to vault root) by default. Use workspace tools (workspace-writeFile, workspace-copy) since this is inside the workspace. Name files descriptively (e.g. " + "`" + "artifacts/Company-Strategy-2025.pptx" + "`" + "). Only use " + "`" + "~/Desktop/" + "`" + " or another path if the user explicitly specifies a different location.",
  "",
  "---",
  "",
  "## Dependencies",
  "",
  `- ${"`"}pip install "markitdown[pptx]"${"`"} - text extraction`,
  `- ${"`"}pip install Pillow${"`"} - thumbnail grids`,
  `- ${"`"}npm install -g pptxgenjs${"`"} - creating from scratch`,
  "- LibreOffice (soffice): PDF conversion",
  "- Poppler (pdftoppm): PDF to images",
].join("\n");

export default skill;
