const BT = "`";

export const reference = [
  "# PDF Processing Skill — Full Reference",
  "",
  "Full API reference for the PDF skill. Loaded on demand via expandSkill('pdf') when detailed code examples are needed.",
  "",
  "## Python Libraries",
  "",
  "### pypdf - Basic Operations",
  "",
  "#### Merge PDFs",
  "```python",
  "from pypdf import PdfWriter, PdfReader",
  "",
  "writer = PdfWriter()",
  "for pdf_file in [\"doc1.pdf\", \"doc2.pdf\", \"doc3.pdf\"]:",
  "    reader = PdfReader(pdf_file)",
  "    for page in reader.pages:",
  "        writer.add_page(page)",
  "",
  "with open(\"merged.pdf\", \"wb\") as output:",
  "    writer.write(output)",
  "```",
  "",
  "#### Split PDF",
  "```python",
  "reader = PdfReader(\"input.pdf\")",
  "for i, page in enumerate(reader.pages):",
  "    writer = PdfWriter()",
  "    writer.add_page(page)",
  "    with open(f\"page_{i+1}.pdf\", \"wb\") as output:",
  "        writer.write(output)",
  "```",
  "",
  "#### Rotate Pages",
  "```python",
  "reader = PdfReader(\"input.pdf\")",
  "writer = PdfWriter()",
  "page = reader.pages[0]",
  "page.rotate(90)",
  "writer.add_page(page)",
  "with open(\"rotated.pdf\", \"wb\") as output:",
  "    writer.write(output)",
  "```",
  "",
  "### pdfplumber - Text and Table Extraction",
  "",
  "#### Extract Text with Layout",
  "```python",
  "import pdfplumber",
  "",
  "with pdfplumber.open(\"document.pdf\") as pdf:",
  "    for page in pdf.pages:",
  "        text = page.extract_text()",
  "        print(text)",
  "```",
  "",
  "#### Extract Tables",
  "```python",
  "with pdfplumber.open(\"document.pdf\") as pdf:",
  "    for i, page in enumerate(pdf.pages):",
  "        tables = page.extract_tables()",
  "        for j, table in enumerate(tables):",
  "            print(f\"Table {j+1} on page {i+1}:\")",
  "            for row in table:",
  "                print(row)",
  "```",
  "",
  "### reportlab - Create PDFs",
  "",
  "#### Basic PDF Creation",
  "```python",
  "from reportlab.lib.pagesizes import letter",
  "from reportlab.pdfgen import canvas",
  "",
  "c = canvas.Canvas(\"hello.pdf\", pagesize=letter)",
  "width, height = letter",
  "c.drawString(100, height - 100, \"Hello World!\")",
  "c.save()",
  "```",
  "",
  "#### Create PDF with Multiple Pages",
  "```python",
  "from reportlab.lib.pagesizes import letter",
  "from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak",
  "from reportlab.lib.styles import getSampleStyleSheet",
  "",
  "doc = SimpleDocTemplate(\"report.pdf\", pagesize=letter)",
  "styles = getSampleStyleSheet()",
  "story = []",
  "title = Paragraph(\"Report Title\", styles[\"Title\"])",
  "story.append(title)",
  "story.append(Spacer(1, 12))",
  "story.append(PageBreak())",
  "doc.build(story)",
  "```",
  "",
  "#### Subscripts and Superscripts",
  "",
  "IMPORTANT: Never use Unicode subscript/superscript characters in ReportLab PDFs. Use XML markup tags:",
  "",
  "```python",
  "from reportlab.platypus import Paragraph",
  "",
  "# Subscripts: use <sub> tag",
  "chemical = Paragraph(\"H<sub>2</sub>O\", styles[\"Normal\"])",
  "",
  "# Superscripts: use <super> tag",
  "squared = Paragraph(\"x<super>2</super>\", styles[\"Normal\"])",
  "```",
  "",
  "### Command-Line Tools",
  "",
  "#### pdftotext (poppler-utils)",
  "```bash",
  "pdftotext input.pdf output.txt",
  "pdftotext -layout input.pdf output.txt",
  "pdftotext -f 1 -l 5 input.pdf output.txt",
  "```",
  "",
  "#### qpdf",
  "```bash",
  "# Merge",
  "qpdf --empty --pages file1.pdf file2.pdf -- merged.pdf",
  "# Split pages",
  "qpdf input.pdf --pages . 1-5 -- pages1-5.pdf",
  "# Rotate",
  "qpdf input.pdf output.pdf --rotate=+90:1",
  "# Remove password",
  "qpdf --password=mypassword --decrypt encrypted.pdf decrypted.pdf",
  "```",
  "",
  "### Extract Text from Scanned PDFs (OCR)",
  "```python",
  "import pytesseract",
  "from pdf2image import convert_from_path",
  "",
  "images = convert_from_path(\"scanned.pdf\")",
  "text = \"\"",
  "for i, image in enumerate(images):",
  "    text += f\"Page {i+1}:\\n\"",
  "    text += pytesseract.image_to_string(image)",
  "    text += \"\\n\\n\"",
  "```",
  "",
  "### Add Watermark",
  "```python",
  "watermark = PdfReader(\"watermark.pdf\").pages[0]",
  "reader = PdfReader(\"document.pdf\")",
  "writer = PdfWriter()",
  "for page in reader.pages:",
  "    page.merge_page(watermark)",
  "    writer.add_page(page)",
  "with open(\"watermarked.pdf\", \"wb\") as output:",
  "    writer.write(output)",
  "```",
  "",
  "### Extract Images",
  "```bash",
  "pdfimages -j input.pdf output_prefix",
  "```",
  "",
  "### Password Protection",
  "```python",
  "reader = PdfReader(\"input.pdf\")",
  "writer = PdfWriter()",
  "for page in reader.pages:",
  "    writer.add_page(page)",
  "writer.encrypt(\"userpassword\", \"ownerpassword\")",
  "with open(\"encrypted.pdf\", \"wb\") as output:",
  "    writer.write(output)",
  "```",
  "",
  "## Filling PDF Forms",
  "",
  "**CRITICAL: Complete these steps in order.**",
  "",
  "1. Check if PDF has fillable fields: `python scripts/check_fillable_fields <file.pdf>`",
  "2. If fillable: extract field info with `extract_form_field_info.py`, create field_values.json, fill with `fill_fillable_fields.py`",
  "3. If non-fillable: use structure extraction (`extract_form_structure.py`) or visual estimation (convert to images, zoom refine)",
  "4. Validate bounding boxes: `python scripts/check_bounding_boxes.py fields.json`",
  "5. Fill: `python scripts/fill_pdf_form_with_annotations.py <input.pdf> fields.json <output.pdf>`",
  "6. Verify: convert filled PDF to images and check text placement",
  "",
  "## Advanced Reference",
  "",
  "### pypdfium2 Library",
  "Render PDF to images, extract text, batch process. High-performance PDFium binding.",
  "",
  "### pdf-lib (JavaScript)",
  "Create and modify PDFs in JS/Node.js. Supports merge, split, text, shapes, form filling.",
  "",
  "### pdfjs-dist (JavaScript)",
  "Mozilla's PDF.js for browser-based PDF rendering and text extraction with coordinates.",
  "",
  "### Advanced Command-Line",
  "- `pdftotext -bbox-layout` — extract text with bounding box coordinates as XML",
  "- `pdftoppm -png -r 300` — high-resolution PNG conversion",
  "- `pdfimages -all -j` — extract all embedded images",
  "- `qpdf --split-pages=N` — split into groups",
  "- `qpdf --linearize` — optimize for web streaming",
  "- `qpdf --encrypt` — add password protection",
  "",
  "### Performance Tips",
  "- Streaming for large PDFs, qpdf for splitting, pdftotext for fast text extraction",
  "- pdfplumber for structured tables, pdfimages faster than rendering for image extraction",
  "- Process large PDFs in chunks (10 pages at a time)",
  "",
  "### Troubleshooting",
  "- Encrypted PDFs: `reader.decrypt(\"password\")`",
  "- Corrupted PDFs: `qpdf --check` / `qpdf --replace-input`",
  "- Scanned PDFs: fall back to OCR (pytesseract + pdf2image)",
  "",
  "## License Information",
  "- pypdf: BSD, pdfplumber: MIT, pypdfium2: Apache/BSD, reportlab: BSD",
  "- poppler-utils: GPL-2, qpdf: Apache, pdf-lib: MIT, pdfjs-dist: Apache",
  "",
  "## Default Output Location",
  "Save final PDF output to " + BT + "artifacts/" + BT + " (relative to vault root). Use " + BT + "tmp/" + BT + " for intermediate files.",
  "",
  "## Dependencies",
  "- " + BT + "pip install pypdf pdfplumber reportlab" + BT,
  "- " + BT + "pip install pytesseract pdf2image" + BT + " - OCR support",
  "- poppler-utils (pdftotext, pdfimages, pdftoppm)",
  "- qpdf, LibreOffice",
  "",
].join("\n");
