export const skill = [
  "# PDF Processing Skill",
  "",
  "Use this skill whenever the user wants to do anything with PDF files: reading/extracting text/tables, merging/splitting, rotating pages, adding watermarks, creating new PDFs, filling forms, encrypting/decrypting, extracting images, OCR.",
  "",
  "## Quick Reference",
  "",
  "| Task | Best Tool |",
  "|------|-----------|",
  "| Merge PDFs | pypdf PdfWriter.add_page |",
  "| Split PDFs | pypdf one page per file |",
  "| Extract text | pdfplumber extract_text |",
  "| Extract tables | pdfplumber extract_tables |",
  "| Create PDFs | reportlab Canvas or Platypus |",
  "| Command line merge | qpdf --empty --pages |",
  "| OCR scanned PDFs | pytesseract + pdf2image |",
  "| Fill PDF forms | See workflow below |",
  "",
  "## Common Workflows",
  "",
  "### Basic PDF Operations (pypdf)",
  "- **Merge:** Iterate source PDFs, add pages via `PdfWriter.add_page()`, write output",
  "- **Split:** One page per file, each in a new `PdfWriter`",
  "- **Rotate:** `page.rotate(90)` before adding to writer",
  "- **Encrypt:** `writer.encrypt(user_pw, owner_pw)` before writing",
  "",
  "### Text & Table Extraction (pdfplumber)",
  "- Open with `pdfplumber.open()`, iterate pages",
  "- `page.extract_text()` for text, `page.extract_tables()` for tables",
  "- Custom table settings: vertical_strategy, horizontal_strategy, snap_tolerance",
  "",
  "### Creating PDFs (reportlab)",
  "- Simple: `canvas.Canvas()` with `drawString()` for basic text",
  "- Complex: `SimpleDocTemplate` + Platypus elements (Paragraph, Table, PageBreak)",
  "- **Never use Unicode sub/superscript** — use `<sub>`/`<super>` XML tags in Paragraph",
  "",
  "### Command Line (qpdf / poppler-utils)",
  "- `qpdf --empty --pages file1.pdf file2.pdf -- merged.pdf` — merge",
  "- `qpdf input.pdf --pages . 1-5 -- out.pdf` — extract pages",
  "- `qpdf --decrypt --password=X encrypted.pdf decrypted.pdf` — remove password",
  "- `pdftotext -layout input.pdf output.txt` — CLI text extraction",
  "",
  "### OCR (Scanned PDFs)",
  "Convert to images with `pdf2image.convert_from_path()`, then OCR each with `pytesseract.image_to_string()`.",
  "",
  "### Filling PDF Forms",
  "1. Check fillability: `python scripts/check_fillable_fields <file.pdf>`",
  "2. Fillable: extract fields → create values JSON → fill script",
  "3. Non-fillable: structure extract or visual estimation → validate → fill",
  "4. Always validate bounding boxes before filling, verify output after",
  "",
  "## Default Output Location",
  "Save to `artifacts/` (relative to vault root). Use `tmp/` for intermediates.",
  "",
  "## Expand for Full Reference",
  "For detailed API code examples (pypdfium2, pdf-lib, pdfjs-dist, advanced qpdf, batch processing, performance tips, troubleshooting), call " + "`" + "expandSkill('pdf')" + "`" + ".",
  "",
  "## Dependencies",
  "- `pip install pypdf pdfplumber reportlab`",
  "- `pip install pytesseract pdf2image` (OCR)",
  "- poppler-utils, qpdf, LibreOffice",
  "",
].join("\n");

export default skill;
