export const skill = [
  "# Web Artifacts Builder Skill",
  "",
  "Build multi-component HTML artifacts using React 18 + TypeScript + Vite + Tailwind CSS + shadcn/ui. Bundle to a single self-contained HTML file.",
  "",
  "Use for complex artifacts requiring state management, routing, or shadcn/ui components. Not for simple single-file HTML/JSX.",
  "",
  "## Workflow",
  "",
  "1. Initialize a frontend project using scripts/init-artifact.sh",
  "2. Develop your artifact by editing the generated code",
  "3. Bundle all code into a single HTML file using scripts/bundle-artifact.sh",
  "4. Present the HTML file to the user",
  "5. (Optional) Test using Playwright if requested",
  "",
  "**Stack**: React 18 + TypeScript + Vite + Parcel (bundling) + Tailwind CSS + shadcn/ui",
  "",
  "## Design & Style Guidelines",
  "",
  "IMPORTANT: Avoid \"AI slop\" — excessive centered layouts, purple gradients, uniform rounded corners, and Inter font.",
  "",
  "### Design System Reference",
  "",
  "When building HTML artifacts, follow the **Paper design system** (see paperdesign.md in project root):",
  "- **Colors**: primary `#111111`, secondary `#8B5CF6` (purple accent), success `#16A34A`, warning `#D97706`, danger `#DC2626`, surface `#FFFFFF`, text `#111827`",
  "- **Fonts**: body = Roboto (sans-serif), display = Montserrat (sans-serif), mono = PT Mono",
  "- **Scale**: 0.875rem/1rem/1.125rem/1.5rem/2rem/2.5rem (14/16/18/24/32/40)",
  "- **Spacing**: 4/8/12/16/24/32",
  "- **Visual style**: minimal, clean, high contrast — no excessive shadows or gradients",
  "",
  "### KaTeX (Math Typesetting)",
  "",
  "If the artifact contains mathematical expressions, use KaTeX for rendering:",
  "- Include KaTeX CSS + JS from CDN in the HTML head",
  '- Use `$...$` for inline math, `$$...$$` for display math',
  "- Full LaTeX notation: fractions, integrals, matrices, Greek letters",
  "- CDN: `https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/` (katex.min.css + katex.min.js + auto-render.min.js)",
  "- Initialize auto-render with a DOMContentLoaded listener (NOT defer + onload — that has unreliable timing): wrap renderMathInElement(...) inside document.addEventListener(\"DOMContentLoaded\", function() { ... })",
  "",
  "### Mermaid (Diagrams)",
  "",
  "If the artifact needs diagrams (flowcharts, sequence diagrams, ER diagrams, etc.):",
  "- Include Mermaid JS from CDN: `https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js`",
  "- Initialize with `mermaid.initialize({ startOnLoad: true, securityLevel: \"loose\" })`",
  "- Use `<pre class=\"mermaid\">` blocks for diagram syntax",
  "- Supported types: graph, sequenceDiagram, classDiagram, erDiagram, gantt, pie, stateDiagram-v2, gitGraph",
  "",
  "Use Mermaid for structured diagrams; use inline SVG for custom illustrations requiring precise positioning.",
  "",
  "## Quick Start",
  "",
  "### Step 1: Initialize Project",
  "",
  "```bash",
  "bash scripts/init-artifact.sh my-artifact",
  "cd my-artifact",
  "```",
  "",
  "This creates a fully configured project with:",
  "- React + TypeScript (via Vite)",
  "- Tailwind CSS 3.4.1 with shadcn/ui theming",
  "- Path aliases (@/) configured",
  "- 40+ shadcn/ui components pre-installed",
  "- All Radix UI dependencies",
  "- Parcel configured for bundling",
  "- Node 18+ compatibility",
  "",
  "### Step 2: Develop Your Artifact",
  "",
  "Edit the generated source files. Build your UI using React components and shadcn/ui.",
  "",
  "### Step 3: Bundle to Single HTML File",
  "",
  "```bash",
  "bash scripts/bundle-artifact.sh",
  "```",
  "",
  "Creates bundle.html - a self-contained artifact with all JS, CSS, and dependencies inlined. Can be shared directly.",
  "",
  "The script:",
  "- Installs bundling deps (parcel, @parcel/config-default, html-inline)",
  "- Creates .parcelrc config with path alias support",
  "- Builds with Parcel (no source maps)",
  "- Inlines all assets into single HTML using html-inline",
  "",
  "### Step 4: Share with User",
  "",
  "Present the bundled HTML file to the user.",
  "",
  "### Step 5: Testing (Optional)",
  "",
  "Only test if necessary or requested. Use Playwright or other tools to verify the artifact works.",
  "",
  "## Reference",
  "",
  "- shadcn/ui components: https://ui.shadcn.com/docs/components",
  "",
  "## Default Output Location",
  "",
  "When building HTML artifacts, save the final bundle.html to " + "`" + "artifacts/" + "`" + " (relative to vault root) by default. Use workspace tools since this is inside the workspace. Name files descriptively (e.g. " + "`" + "artifacts/dashboard.html" + "`" + "). Only use " + "`" + "~/Desktop/" + "`" + " if the user explicitly asks.",
  "",
  "## Dependencies",
  "",
  "- Node.js 18+",
  "- npm",
  "- bash (for init/bundle scripts)",
].join("\n");

export default skill;
